### ISSUE TITLE
XML reader saying there are errors. Unsure if issue.

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#103]
My XML reader comes up with a few errors that I'm not sure whether they are issues or not, but I wanted to bring them to the attention of @CCDevNelson and others to let me know what they mean. I took a screenshot because GitHub won't let me attach an XML, but I can send the XML to you if you'd like. Here are the errors:

1. "The element 'Item' has invalid child element 'Part'. List of possible elements expected: 'Assembly, Var'."

2. "Reference to undeclared ID is 'IDP-155'" (every IDP from 56 to 155).

![image](https://user-images.githubusercontent.com/61025894/86280876-796c1580-bb91-11ea-9d7a-9992ae4b2898.png)

**Comment by RyanMDev** [comment]
When you expand the `Item` node, are the `Part` nodes and `Assembly` nodes grouped together or unordered?

**Comment by TEDSTANDAGE** [comment]
Here's what I have under "Item":

![image](https://user-images.githubusercontent.com/61025894/86394375-55710880-bc53-11ea-991a-573fbcb492cc.png)

**Comment by TEDSTANDAGE** [comment]
I believe Mark said that IDPs 15 to 55 aren't showing up as parts when running through CADcode (IDP 15 is the first part of the first assembly), then the IDP errors start at 56 and go through the rest of the IDPs (through 155). IDP-56 is the first part after that first group of assemblies you see above.

**Comment by RyanMDev** [comment]
I see, I believe the schema is expecting all `Part` nodes to come before `Assembly` nodes.

Try and reorder these nodes so that `Part` nodes are grouped together before `Assembly` nodes and see if that fixes the error.

**Comment by RyanMDev** [comment]
Could you share a link to the XML?

**Comment by CCDevNelson** [comment]
[TollBrotherJob.zip](https://github.com/CCDevNelson/Snap-Updates/files/4866028/TollBrotherJob.zip)

**Comment by TEDSTANDAGE** [comment]
No errors from me from @RyanMDev 's new XML in https://github.com/CCDevNelson/SNaP-Dev/issues/221

![image](https://user-images.githubusercontent.com/61025894/86425936-4c0b8e80-bc9b-11ea-97d0-f0d5a6f34d2a.png)

**Comment by TEDSTANDAGE** [comment]
Teddy @ClassyTeddy , can you ask Ryan to merge the new updated CSV? His XML has the old material name output (Oxford White 15200) when it needs to be just Oxford White like was in mine (I had changed the CSV in my version when I had exported the XML previously).

Mark @CCDevNelson , can you please test the XML with CADCode, etc. and let us know if you get the same errors? If it doesn't fail like last time, then we just need to fix the above and then I think we can give this job a go through the shop unless there are other issues you can think of.

Hoping to have this cleaned up today so we can optimize the job tomorrow. 

Thank you everyone, 

Ted

**Comment by TEDSTANDAGE** [comment]
Teddy is out for a day or two so Mark @CCDevNelson , if you can please change the color from Oxford White 15200 to just Oxford White in the XML before you run it through CADcode, etc., I'd appreciate it. Obviously we will want to have Ryan's fix of what was causing the XML issues in place for future testing, but at least we can get this job through to test the drilling and the other fixes we have made to this point. Thanks, Ted

**Comment by CCDevNelson** [comment]
Ted,

 

              I need an XML file to test.

 

              Please have someone draw a room with at least 1 or 2 double drilled partitions.

 

Mark

**Comment by TEDSTANDAGE** [comment]
https://github.com/CCDevNelson/SNaP-Dev/issues/221#issuecomment-653251735

**Comment by TEDSTANDAGE** [comment]
Ryan has a fixed XML in the comment referenced above, this is for the Toll Bros job we have been working to test this past week.

**Comment by CCDevNelson** [comment]
Looking at the modified XML you sent me, there is a problem that I am now picking up with edge banding.
There are several parts exporting with L1 and L2 that should NOT have edge banding on the second L2 side.
![EdgebandErr](https://user-images.githubusercontent.com/44483142/86628500-d2b3ba80-bf7e-11ea-93fb-7b7a013ce6bf.png)

**Comment by TEDSTANDAGE** [comment]
Thank you Mark. Can you let us know which parts you saw that are coming up with the incorrect second L2 so we can look into it?

**Comment by TEDSTANDAGE** [comment]
I just looked at every label in the modified XML from Ryan and the only parts I saw with both L1 and L2 were cover cleat, which would have both L's edged. Let me know if I missed something though. 

Now, if the fix from https://github.com/CCDevNelson/Snap-Updates/issues/86 that was supposed to keep it from exporting white/almond cover cleat isn't working we can address that, but it shouldn't hold us up from going forward with testing this job. It will be okay to manufacture the cover cleat for this test job.

**Comment by CCDevNelson** [comment]
Since when have we edgebanded both side of Cover Cleat? That's a new one on me, but yes, you are correct in that the parts all seem to be Cover Cleat in the XML export, I am however, getting several Adj. Shelves with edgebanding on L1 and L2 when I read in the XML. So something is "triggering" my code to go out and find info for those parts. I'll have to get deeper into my code to figure out why that is.
I have no idea if the fix from #86 is working since I haven't seen a new XML file with that.

**Comment by TEDSTANDAGE** [comment]
Thanks Mark. When you're able to locate which adjustable shelves you're seeing that have both L1 and L2 let us know so we can address it.

I was also mistaken on cover cleat being edged on both long edges, so that is my fault. I will have Teddy change the cover cleat XML export logic to only have 1 long edge since he had that 2 long edge logic in there based on what I asked him to do previously.

This XML file was made with the fix from #86 that was supposed to change the cover cleat class to "draw" from the "Updated Cover Cleat Export Logic" change dated June 9, 2020. Here is some of the language that was added:

            if(part_name == "Cover Cleat" and (mat_inventory_name == "Oxford White 15200" or mat_inventory_name == "Cabinet Almond 15200")):
            if(part_name == "Cover Cleat" and (("Oxford White" in mat_inventory_name) or ("Cabinet Almond" in mat_inventory_name) or ("Dura White" in mat_inventory_name) or ("Dura Almond" in mat_inventory_name))):
                self.xml.add_element_with_text(elm_part,'Class', "draw")#Str literal okay
            else:
                self.xml.add_element_with_text(elm_part,'Class', "make")#Str literal okay

If this XML is still creating the cover cleat parts to cut and fabricate then it doesn't look like the fix in #86 is doing what we hoped it would.

**Comment by CCDevNelson** [comment]
Ted,
The Adj. Shelves were in my code. On child assemblies I was trying to set the Long and Short edges from "old" XML exports. Just didn't comment out that portion, but it is now and working correctly so the only items are still the Cover Cleats.

When I meant I hadn't seen an XML with that change mention above, I meant I haven't received an XML file from anyone that has those corrections for me to test. I have been using the XML (modified by Ryan) as a current test file.

**Comment by TEDSTANDAGE** [comment]
Okay cool, so we can still run this job to test the drilling? We will just have some extra cover cleat with incorrect edgebanding.

The cover cleat draw/make fix was merged with the master version already so cover cleat should have the class as "draw" rather than "make", but this job's XML still has it as "make" so the fix is not working and we need to take another look at it.

**Comment by CCDevNelson** [comment]
I can manually change those things if that's what you want to do.

Am I using this copy or am I getting another one with the changes?

**Comment by TEDSTANDAGE** [comment]
Yeah, I think we just use this latest copy from Ryan and manually change the material name to "Oxford White" since Ryan's csv didn't have the material name update, and then if manually changing the class of cover cleat to "draw" after the fact will make them not be optimized/cut let's do that as well. Really want to see how the drilling goes. Before the next test after this one we will address the cover cleat export logic, incorrect cover cleat edgebanding, and then whatever Ryan did to reorder the parts/fix the XML errors.
