### ISSUE TITLE
Cover Cleat edge material sku incorrect for White and Almond

### ISSUE THREAD

**Issue by CCDevNelson** [CCDevNelson/Snap-Updates#114]
While testing the latest XML, found that the edge banding sku is incorrect for the Cover Cleat that is White or Almond.
White should be: EB-0000314
and Almond: EB-0000315
These are 5/8" tape used for edgebanding 3/8" Cover Cleat.

**Comment by ClassyTeddy** [comment]
I'll take a look at this. We currently aren't importing those materials ItemTypeCode. Is this true for all edgebanding of cover cleat? Or is White and Almond a separate special case?

**Comment by TEDSTANDAGE** [comment]
If we aren't exporting cover Cleat for white or almond it shouldn't matter though, correct? Once Teddy makes the fix for the "draw" vs "make" distinction for white and almond cover cleat then they won't be cut and manufactured. But, it is good info to know and perhaps we should still make the change just in case we change how we do white and almond cover cleat.

If we need to update the edgeband Sku for other colors' cover cleat edgebanding please let us know.

**Comment by CCDevNelson** [comment]
White and Almond are the ONLY two colors that we run full length strips in bulk. So the material is 3/8" and the Edge banding is 5/8". ALL over Cover Cleat is processed as 3/4" material and uses a 15/16" tape.

**Comment by CCDevNelson** [comment]
If we are wanting the information to be correct for Pricing, Job Costing, Material Ordering, etc. I would think that it needs to be corrected. Those two color make up for a "Ton" of cover cleat and would throw "Material" projections out the window. Price between the two is substantial as well.

**Comment by TEDSTANDAGE** [comment]
Okay that makes a lot of sense. Thank you for that explanation Mark. Changing them from "make" to "draw" won't screw that up correct?

**Comment by CCDevNelson** [comment]
No, that will only affect the Saws....it will just keep those "Cover Cleats" from being optimized and cut on the saws. The pricing and what I send to "BC" is all the other info. The "make" or "draw" is only for CADCode's optimization part.

**Comment by CCDevNelson** [comment]
Along this line of Cover Cleat...the material SKU is incorrect as well. it is currently calling out a 3/4" sku and should be calling out either white: PM-0000001 or almond at: PM-0000002.
I know we are talking penny's on the pricing, but for material projections, work orders, BOM's, etc. we should have that corrected as well.

**Comment by ClassyTeddy** [comment]
So cover cleat for white and almond needs both the material and the edgebanding material changed?

**Comment by CCDevNelson** [comment]
In my opinion, yes.
White Cover Cleat : materialsku: PM-0000001  with edgebanding2sku: EB-0000314
Almond Cover Cleat : materialsku: PM-0000002  with edgebanding2sku: EB-0000315

**Comment by ClassyTeddy** [comment]
So when you say white/almond cover cleat, does it include Dura White, Dura Almond, Oxford White, and Cabinet Almond?

**Comment by CCDevNelson** [comment]
I'm pretty sure (99%) that is correct. We use a lot of it, that's why it's run in bulk, usually on the night shift.

**Comment by ClassyTeddy** [comment]
Kk, I'll have to import those materials as well

**Comment by CCDevNelson** [comment]
Just checked, that's a 100% correct.

**Comment by CCDevNelson** [comment]
Question, why?
Can't that just be hard coded for those two color? We are talking basically 4 sku numbers here, right?

**Comment by TEDSTANDAGE** [comment]
I would figure it'd just be a simple XML export logic rule that says if the cover cleat material is white or almond (dura or panolam) that it'd make the cover cleat the particular SKU numbers Mark identified (depending if white/almond and also to make those "draw" and not "make").

**Comment by TEDSTANDAGE** [comment]
Then also double the quantity because the 3/8" won't be ripped like the 3/4" material otherwise would be.

**Comment by ClassyTeddy** [comment]
This issue is ready for testing on the `Cover-Cleat-Export-Changes` branch.

**Comment by TEDSTANDAGE** [comment]
I can't test dura white/almond because of the issue I just posted in #115 , but Oxford White looks to be exporting the correct material and edgebanding material for cover cleat:

![image](https://user-images.githubusercontent.com/61025894/87472808-6287e300-c5d5-11ea-929f-50757145b420.png)

It also looks to be correctly putting them as "draw":

![image](https://user-images.githubusercontent.com/61025894/87472757-4be18c00-c5d5-11ea-93c5-a78d8c0ac7c4.png)


However:

Cabinet Almond looks to be exporting the correct cover cleat name but is putting the wrong SKU number (putting PM-0000001 for the material which is 3/8" white and EB-0000314 which is also white):

![image](https://user-images.githubusercontent.com/61025894/87472610-0de46800-c5d5-11ea-86a8-7e873169dd09.png)


The number of cover cleat lengths exported also doesn't seem to be doubling the amount of cover cleats needed. My test exported 5 lengths which would be correct if it was the regular 3/4" material. Because the amount of cover cleat will be doubled under this, there should never be an odd number of cover cleat lengths.

**Comment by ClassyTeddy** [comment]
Looks like I had a couple typos. Check it out now. I think it is working for both white and almond, and it should be doubling now.
