### ISSUE TITLE
When I close out Toggle System Console it exits out of SNaP completely

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#147]
As the title states, when I close out of the Toggle System Console it also shuts down the entire SNaP/blender program. It'd be nice if that didn't happen. I can minimize the Toggle System Console but cannot close the window without also exiting SNaP.

**Comment by RyanMDev** [comment]
This is normal.

The system console **\*is\*** the running SNaP process.

In fact, closing the SNaP program from the main interface redirects to closing this system console window/process if it is shown or not.

So closing the system console window is more like "super" quit.

The console window in SNaP gives you access to the main process and closing this window closes that process. 

This is what happens when a program freezes up and you cannot close it from its own interface, you instead need to go to Windows Task Manager and force quit the program killing the process.

**Comment by TEDSTANDAGE** [comment]
Alright, understood and it makes sense. So it sounds like it's not possible to change and if someone is going to open the toggle system console they should just be ready to have it open until they are ready to close down the program.
