### ISSUE TITLE
Flat Crown improvements

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#148]
Right now SNaP just draws returns butting up to the front piece of crown (leaving an exposed end of the front piece of crown, requiring the user to select "exposed left" to cover the particle board end with edgebanding when in reality it will not be exposed and does not need edgebanding) rather than the two pieces being mitered and the corners meeting for a clean look and no edgebanding on the sides:

![image](https://user-images.githubusercontent.com/61025894/90553785-cad46200-e149-11ea-9894-272da62daae2.png)

For drawing purposes it's not the end of the world to just select that the end is exposed so that you don't see the particle board, but I am about to request changes in exporting flat crown lengths (similar to cover cleat lengths) where having exposed ends will change how the flat crown is exported, so this needs to be addressed to show a clean corner for returns of the flat crown without needing to select that it is an exposed end. 

Also for the flat crown to have the top edgebanded the flat crown needs to be a minimum of 3" tall. 

Need to create "Variable height" option for flat crown to the ceiling (add 2" to height in XML export if this option is selected) and there cannot be edgebanding on the top of the crown if this is selected.

- [x] Create miter for flat crown returns

- [x] Require 3" minimum height for flat crown to have top edge edgebanded.

- [x] Create "Variable height" option for flat crown to the ceiling (add 2" to height in XML export if this option is selected) and there cannot be edgebanding on the top of the crown if this is selected.

**Comment by TEDSTANDAGE** [comment]
The installer will ultimately perform the miter cut so that info does not need to be added to the item, we just need to have enough lengths for them to have enough material to make the cut which we will build into the XML export logic. If the two pieces need to overlap eachother the 0.75" to create the clean look in the drawings without requiring edgebanding that is fine.

**Comment by TEDSTANDAGE** [comment]
With the "variable height" option -- we should just make this an "Extend to Ceiling" option so the crown just automatically is extended up to the wall height. Then have the variability (adding 2") come out in the XML. With the "Extend to Ceiling" option, there must always be a top KD in the partitions of the sections it covers.

- [ ] Add options for "Top KD 1 hole down" and "Top KD 2 holes down" where it moves the top KD down a hole (or two) and the flat crown is extended down accordingly. Not sure if this option needs to be in the partition construction options or if the flat crown prompts can take care of it. If it's in the partition construction options, then the flat crown needs to recognize when the partition prompts have that selected and it should be placed vertically accordingly.

**Comment by ClassyTeddy** [comment]
I have a question. Is there ever a scenario where flat crown will not cover the entire length of the partition? Like all the sections and what not?

**Comment by TEDSTANDAGE** [comment]
Teddy, to recap our phone conversation, there are times when one section will be open to account for a vent or a light, but it is not the most common scenario. For now, if it makes it easier to just turn on all top KDs to account for the flat crown let's go ahead and do it and then we can figure out a fix for those uncommon scenarios in a later issue.

**Comment by ClassyTeddy** [comment]
I believe I have addressed everything here and it is ready for testing on the `Flat-Crown-And-Crown-Molding-Improvements` branch.

**Comment by TEDSTANDAGE** [comment]
Thank you Teddy. A few things:

1. the left and right returns are not taking into account the Extend to Ceiling and Top KD Holes Down prompts:

![image](https://user-images.githubusercontent.com/61025894/94302256-c78a7e00-ff20-11ea-9c60-14aa39789058.png)

2. if there are returns, the ends of the front should be extended 0.75". 

3. the default for "extend ends" should be 0.

4. the top KDs are not currently automatically put in after extending to the ceiling--you have to then go to the construction options of the partition prompts then they automatically turned on, and the top KDs don't move to the location selected in the flat crown prompts until you go into the construction options of the partition prompts if you decide to change the location. The top KD should move as you change the prompts in the flat crown menu.

5. the front piece looks like it always has edgebanding on all four sides even if none of the "exposed edges" buttons are selected, it should not be this way, it should only have edgebanding on the sides selected (and the bottom edge)

![image](https://user-images.githubusercontent.com/61025894/94303223-53e97080-ff22-11ea-857e-5cece7d346c3.png)

6. if I do "Extend to Ceiling", move the top KD down, and then change my mind and don't extend to ceiling, then the top KD is stuck at where the last location selected in those prompts was

7. the top cleat of the openings also needs to move down with the top KD when the top KD's location is changed.

![image](https://user-images.githubusercontent.com/61025894/94303178-4338fa80-ff22-11ea-9fad-dfd8b333774c.png)

8. Doors and other assemblies need to take into account the location of the top KD when being placed and when sizing for "fill opening"

![image](https://user-images.githubusercontent.com/61025894/94303448-ab87dc00-ff22-11ea-8f5a-9553249c7ab0.png)

9. Backs need to take into account the location of the top KD if it is moved down

![image](https://user-images.githubusercontent.com/61025894/94303520-d07c4f00-ff22-11ea-8bb7-3efc1526f584.png)

**Comment by TEDSTANDAGE** [comment]
Sorry, I know it's easy to point out all the things wrong. I think it's a good start and the extend to ceiling option is great--it obviously just creates a new factor for everything else around it to take into consideration. Thank you for your work on this. If you need to break out the above things into separate issues to keep it all straight please feel free to do so

**Comment by TEDSTANDAGE** [comment]
With the exported height of the variable flat crown when it is extended to the ceiling, I think there are some issues. First, I am not sure what this means when the flat crown "depth" as shown on the right column says 0.27" and I think there are issues with the other sizing/dimensions of the piece as well:

![flat crown dimensions](https://user-images.githubusercontent.com/61025894/94304923-38cc3000-ff25-11ea-83f1-2c323ebb480c.png)

This piece should be 73.5" wide (72" partitions & openings + 1.5" total of extension for L/R) X 3.52" tall (0.75" ceiling to top of partition + 0.25" overhang of KD + 2.52" for being two holes down (1.26" per hole)) X 0.75" (thickness of material) (I understand that the dimensions in that menu are going to change up what the width/depth/height refer to, but these numbers are not reflected there)

The XML export of the flat crown in this is also showing it as 3.27" tall rather than  5.52" (3.52" plus 2" variable since it is extended to the ceiling):

![image](https://user-images.githubusercontent.com/61025894/94305532-2c94a280-ff26-11ea-9410-1e50b1497834.png)

**Comment by ClassyTeddy** [comment]
> the top KDs are not currently automatically put in after extending to the ceiling--you have to then go to the construction options of the partition prompts then they automatically turned on, and the top KDs don't move to the location selected in the flat crown prompts until you go into the construction options of the partition prompts if you decide to change the location. The top KD should move as you change the prompts in the flat crown menu.

So it is actually set up so that the change is made whenever you make ANY change in the prompts menu of the Partition OR when you save the file. I can ask @RyanMDev if it would be possible to have the changes run automatically by triggering the Partitions Check function remotely, but I do not know if that is possible. 

> the front piece looks like it always has edgebanding on all four sides even if none of the "exposed edges" buttons are selected, it should not be this way, it should only have edgebanding on the sides selected (and the bottom edge)

I had actually just removed the CORE material for the all sides of the flat crown, trying my best to give the sides the mitered look, without overlapping the parts. This also means removing it on the top. The actual edgebanding is still determined by what the user selects is an exposed end. Will this be a problem and need to be reverted?

> With the exported height of the variable flat crown when it is extended to the ceiling, I think there are some issues. First, I am not sure what this means when the flat crown "depth" as shown on the right column says 0.27" and I think there are issues with the other sizing/dimensions of the piece as well:

So the Width, Depth, and Height displayed there are not the actual dimensions of the individual parts, those are the dimensions of the whole assembly. The dimensions of the assembly are not used when exporting, we get the dimensions of the parts. 

> This piece should be 73.5" wide (72" partitions & openings + 1.5" total of extension for L/R) X 3.52" tall (0.75" ceiling to top of partition + 0.25" overhang of KD + 2.52" for being two holes down (1.26" per hole)) X 0.75" (thickness of material) (I understand that the dimensions in that menu are going to change up what the width/depth/height refer to, but these numbers are not reflected there)

So I have one question about this part. obviously the calculation is incorrect here but I am curious if this would be the minimum height. Because we do currently allow the user to just set the height of the Flat crown, it's height just defaults to 3 inches. Should it default to these calculations instead and we allow the user to extend it?

> if I do "Extend to Ceiling", move the top KD down, and then change my mind and don't extend to ceiling, then the top KD is stuck at where the last location selected in those prompts was

So, I had set it up so it should have been trying to revert automatically, which isn't working and I will take a look at, but should I also add a section in the Partition prompts that allows users to change the Top KD's position whenever? In which case, should I extend the amount of holes it can be lowered? Or is it only rarely lowered with Flat Crown.

I will tackle all of this after I add the option for inverted base on Crown molding if that is ok.

**Comment by TEDSTANDAGE** [comment]
> > the top KDs are not currently automatically put in after extending to the ceiling--you have to then go to the construction options of the partition prompts then they automatically turned on, and the top KDs don't move to the location selected in the flat crown prompts until you go into the construction options of the partition prompts if you decide to change the location. The top KD should move as you change the prompts in the flat crown menu.
> 
> So it is actually set up so that the change is made whenever you make ANY change in the prompts menu of the Partition OR when you save the file. I can ask @RyanMDev if it would be possible to have the changes run automatically by triggering the Partitions Check function remotely, but I do not know if that is possible.

Alright, would think we would want it to happen when the request/change is made, and not have to wait until some later unrelated action.

> 
> > the front piece looks like it always has edgebanding on all four sides even if none of the "exposed edges" buttons are selected, it should not be this way, it should only have edgebanding on the sides selected (and the bottom edge)
> 
> I had actually just removed the CORE material for the all sides of the flat crown, trying my best to give the sides the mitered look, without overlapping the parts. This also means removing it on the top. The actual edgebanding is still determined by what the user selects is an exposed end. Will this be a problem and need to be reverted?

Yes, let's go back to the core material--we need people to see whether they edgebanded an end or not, otherwise a user likely will miss exposing necessary ends. Also, we need to overlap the pieces to get the correct lengths for a miter to be able to happen (though we are exporting lengths and already add an extra length so it doesn't necessarily need to be perfect, but it will be more accurate when calculating the amount of flat crown needed). 

> 
> > With the exported height of the variable flat crown when it is extended to the ceiling, I think there are some issues. First, I am not sure what this means when the flat crown "depth" as shown on the right column says 0.27" and I think there are issues with the other sizing/dimensions of the piece as well:
> 
> So the Width, Depth, and Height displayed there are not the actual dimensions of the individual parts, those are the dimensions of the whole assembly. The dimensions of the assembly are not used when exporting, we get the dimensions of the parts.

How is the assembly 0.27" deep and -0.75" tall then? That doesn't make sense to me. 

> 
> > This piece should be 73.5" wide (72" partitions & openings + 1.5" total of extension for L/R) X 3.52" tall (0.75" ceiling to top of partition + 0.25" overhang of KD + 2.52" for being two holes down (1.26" per hole)) X 0.75" (thickness of material) (I understand that the dimensions in that menu are going to change up what the width/depth/height refer to, but these numbers are not reflected there)
> 
> So I have one question about this part. obviously the calculation is incorrect here but I am curious if this would be the minimum height. Because we do currently allow the user to just set the height of the Flat crown, it's height just defaults to 3 inches. Should it default to these calculations instead and we allow the user to extend it?

The height of "Extend to Ceiling" flat crown should be as I calculated (which is the size shown in the scene plus a 2" variable since it is to the ceiling). 3" should be a minimum for flat crown.

> 
> > if I do "Extend to Ceiling", move the top KD down, and then change my mind and don't extend to ceiling, then the top KD is stuck at where the last location selected in those prompts was
> 
> So, I had set it up so it should have been trying to revert automatically, which isn't working and I will take a look at, but should I also add a section in the Partition prompts that allows users to change the Top KD's position whenever? In which case, should I extend the amount of holes it can be lowered? Or is it only rarely lowered with Flat Crown.

There needs to be a way to drop the top KD for crown molding as well, and we will need the option when we eventually add lighting options, so perhaps it would be easier to just add the option in the partition prompts as well. Not sure if that will help with some of the auto-movement issues of the top KD as well from the flat crown / crown molding prompts?
> 
> I will tackle all of this after I add the option for inverted base on Crown molding if that is ok.

That's fine, thank you Teddy

**Comment by TEDSTANDAGE** [comment]
> > > With the exported height of the variable flat crown when it is extended to the ceiling, I think there are some issues. First, I am not sure what this means when the flat crown "depth" as shown on the right column says 0.27" and I think there are issues with the other sizing/dimensions of the piece as well:
> > 
> > 
> > So the Width, Depth, and Height displayed there are not the actual dimensions of the individual parts, those are the dimensions of the whole assembly. The dimensions of the assembly are not used when exporting, we get the dimensions of the parts.
> 
> How is the assembly 0.27" deep and -0.75" tall then? That doesn't make sense to me.

Nevermind, I found where the object/particular piece dimensions are. Disregard this comment by me

**Comment by ClassyTeddy** [comment]
The following changes are ready for testing on the `Flat-Crown-and-Crown-Molding-Improvements` branch.
- The left and right returns are now properly placed and take into account the `Extend to Ceiling` and `Top KD Holes Down` prompts
- The default for extend ends is now 0"
- The front now extends the associated end by 0.75" when there is a return
- Top KD's are now automatically put in and adjusted (Found a way to have it happen immediately without opening the partition prompts)
- The edgebanding of the piece now shows the core material for sides not marked with exposed ends
- The returns are now extended and clip with the front in order to make it appear mitered and to not reveal core
- The Top KD now returns to the default position when the 'Extend to Ceiling' option is unselected
- The top cleat, opening, other assemblies, and backing now adjust to the Top KD being lowered
- The Flat Crown and Returns heights are now properly adjusted with a variable 2" when exported.
- The flat crowns height now takes into account the 0.25" for the KD overhang (This and the above point are why it was coming out to 3.27" instead of 5.52")

**Comment by TEDSTANDAGE** [comment]
This is looking really good Teddy, thank you. @JBTattersall @kategodfrey have you guys tested this yet? Please do if you haven't.

**Comment by JBTattersall** [comment]
I tested this with a top shelf not all the way to the ceiling. I received some (4) errors on a complicated closet. I tried to capture the errors but I moved my mouse and they disappeared. I believe those were my fault because it worked fine on a couple of easier closets.
