### ISSUE TITLE
Change XML Export logic for flat crown to export full lengths

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#152]
Unless a flat crown has two exposed ends, the crown should be exported as full lengths. If there is flat crown with one exposed short end, then there needs to be a full length that is exported with a short end edgebanded. Exposed short ends on flat crown are rarer because of how we miter corners, but they do happen.

- For each room exported, add together all the lengths of flat crown that don't have both left and right ends exposed, divide by 96", then round up to the next whole number. Then, if that whole number is 1-2 lengths of flat crown, add one extra length. If the number is 3-5 lengths, add two extra lengths. If the number is 6 or more lengths, add three extra lengths. 
- If there are flat crown pieces with a single exposed left or right end then the number of exported lengths with a short end edgebanded needs to equal the number of single left/right exposed end pieces.
- Flat crown pieces with both left and right ends exposed need to be exported exactly at length (and not counted in the above equation) unless it is greater than 96" inches, in which case enough full lengths of flat crown need to be exported for that run of crown with two of those exported lengths having a single short end edgebanded.

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Flat-Crown-And-Crown-Molding-Improvements` branch.

**Comment by TEDSTANDAGE** [comment]
It is exporting full lengths now, thank you. I do not think it is calculating correctly though. For example, here is a room with a run of 120" of Flat Crown plus two 55" runs (with left and right 12" returns). In the XML, only 3 lengths were exported and they were named "Right" (I assume from the right return part?):

![image](https://user-images.githubusercontent.com/61025894/93508753-a2b85a00-f8d3-11ea-8dae-d1c64b5972a8.png)

![image](https://user-images.githubusercontent.com/61025894/93508767-a815a480-f8d3-11ea-92d5-1d1d4fdd38f3.png)

So, I think we need to make sure it is adding up all Flat Crown parts (front length and return pieces) and then exporting the correct number based on the formula I laid out up front. We also need to name the exported pieces as "Flat Crown" rather than "Right".

Also--We want to make sure the cover cleat calculation isn't including flat crown in its calculation for lengths--for the job above, a total of ten cover cleat lengths were exported, I assume because it was counting the flat crown in its calculation.

**Comment by ClassyTeddy** [comment]
The issue where they were being named Right is because of the returns, should be an easy fix.

The cover cleat lengths exported are not being affected. I believe I was told to double the amount of cover cleat for white/almond materials which is why it seems like a lot.

Did you mark any of the flat crowns as having exposed ends?

**Comment by TEDSTANDAGE** [comment]
> Did you mark any of the flat crowns as having exposed ends?

The tops were "exposed"/edgebanded but none of the ends (L/R) were exposed. Perhaps that's where the issue is--only the left and right should be considered "ends", but if the three fronts were those parts then there should have been at least another length or two to cover the returns, and the run of 120" would have needed two pieces itself. 

And I guess it should be differentiating between flat crown with 2L edges and flat crown with only 1L when it is determining how many lengths of each to export. Usually a closet will only have one or the other, but it does happen where there will be some crown that has 2L and some only 1L within the same closet.


> The cover cleat lengths exported are not being affected. I believe I was told to double the amount of cover cleat for white/almond materials which is why it seems like a lot.

Okay, we may want to look into the cover cleat export logic again but I will do some more testing and create a separate issue.

**Comment by TEDSTANDAGE** [comment]
Also, the XML export only had 1L to be edgebanded when it should have had 2L.

Then, I just tried exposing one of the 55" flat crown fronts on the left and still got 3 lengths exported with one of them having 1L/1S (which is good). When I exposed it on both the left and right, however, no XML was created upon attempting to export it.

**Comment by ClassyTeddy** [comment]
Alright, I will take a look. 

I looked at the cover cleat logic and realised why there are so many. So I did the calculation of adding up all the cover cleat, dividing by 96, then dividing again by 2 because of the fact that you split the 3/4" cover cleat into 3/8". Then it rounds up and the extra lengths are added. Then it multiplies by 2 if the material is white/almond. I'll fix it so it multiplies by 2 before the extra lengths are added, then that should calculate to the right amount.

**Comment by ClassyTeddy** [comment]
Also, it looks like the top edgebanding isn't working because of some of the early changes I made with Flat Crown Improvements. It currently isn't checking to see if the top is edge banded or not, it is just always exporting flat crown with 1L.

**Comment by CCDevNelson** [comment]
Teddy, on White or Almond, the material is already 3/8" material. We do NOT split White or Almond Cover Cleat.

**Comment by ClassyTeddy** [comment]
Right, which is why I was told to double the amount of needed lengths for White or almond. But I doubled it after the addition of more lengths rather than before.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Flat-Crown-and-Crown-Molding-Improvements` branch

**Comment by TEDSTANDAGE** [comment]
This is looking good as well. I do have a question about how it handles if someone puts two different sizes of flat crown in the same closet (not ideal design-wise, but there may be a time when it is necessary). I would think it should use separate export logic for like-sized flat crown rather than just all flat crown in the room generally. I did a closet with different sized flat crowns and it only exported one size of flat crown for the lengths that were exported (if it was a a double-exposed flat crown it correctly exported separately though). Is it possible to get more specific with it?

**Comment by TEDSTANDAGE** [comment]
Let's adjust the equation a bit too for flat molding without any exposed ends:

If there is only one run of molding (including no returns) and it is less than 93", only export one length of molding.

If there is more than one piece of molding and/or if the one piece is greater than 93" long, then add together all the particular molding in the room, divide by 96", then round up to the next whole number. If that whole number is 1-3 lengths, add one extra length. If the number is 4-6 lengths, add two extra lengths. If the number is 7 or above, add three extra lengths.

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Flat-Crown-and-Crown-Molding-Improvements` branch.

**Comment by TEDSTANDAGE** [comment]
Tested some flat crown today and ran into some issues on the export. Also pertains to https://github.com/CCDevNelson/Snap-Updates/issues/148.

In this job I have 3 different flat crown heights:

![image](https://user-images.githubusercontent.com/61025894/96613345-b2043c00-12b3-11eb-9d8b-3e92117cfe60.png)

1. The left wall has a 54x4 flat crown edged 2L/2S. That exported fine.

2. The center wall has flat crown to the ceiling, the partition sitting 0.75" from ceiling and the top KD one hole down (so the crown is 2.26" tall), left and right returns, and the front piece should be 91.5" wide and the returns 12.75" deep. SNaP is showing the front piece as 91.49" instead of 91.50" for some reason:

![91 49](https://user-images.githubusercontent.com/61025894/96613705-20e19500-12b4-11eb-9ac7-de78c9982b42.png)

The XML export has 2 lengths of 6.26" tall flat crown, which I assume is this wall's crown? Though, it should have exported three lengths (91.50+12.75+12.75 = 117, divide by 96 = 1.22, round up to 2 lengths, add one extra length because it is 1-3 lengths getting us to 3 lengths). Also, it should have only added 2" to the height, not 4", putting it at 4.26" tall rather than 6.26".

3. The right wall has flat crown to the ceiling, the partition sitting 0.75" from ceiling and the top KD at the top of the partition and not down a hole (so the crown is 1" tall), left and right returns, and the front piece should be 55.50" wide and the returns 12.75" deep. Like the other wall, SNaP is showing the front piece as 55.49" instead of 55.50" for some reason.

The XML Export has 2 lengths of 6.00" tall flat crown (which is the correct number of lengths) but also there is 1 length of 5.00" tall flat crown? Unsure what is causing that. The flat crown here should be 3.00" tall, not 6".

I am unsure exactly where the issue lies, but let me know if you have any questions about the job to help figure it out.

Thanks, 

Ted

![image](https://user-images.githubusercontent.com/61025894/96616906-c77b6500-12b7-11eb-8a10-26aba476ee55.png)

![image](https://user-images.githubusercontent.com/61025894/96616926-ce09dc80-12b7-11eb-9a6d-b7df9b6a5467.png)

![image](https://user-images.githubusercontent.com/61025894/96616938-d3672700-12b7-11eb-8ad1-dfb2480dc97e.png)

**Comment by ClassyTeddy** [comment]
> The center wall has flat crown to the ceiling, the partition sitting 0.75" from ceiling and the top KD one hole down (so the crown is 2.26" tall), left and right returns, and the front piece should be 91.5" wide and the returns 12.75" deep. SNaP is showing the front piece as 91.49" instead of 91.50" for some reason:

The front piece is actually 91.49999", but your window is small so it just displays the first 9, The reason I subtracted a very small distance is to create the mitered look without clipping, and the amount is so small that it won't affect rounding errors.

> The XML export has 2 lengths of 6.26" tall flat crown, which I assume is this wall's crown? Though, it should have exported three lengths (91.50+12.75+12.75 = 117, divide by 96 = 1.22, round up to 2 lengths, add one extra length because it is 1-3 lengths getting us to 3 lengths). Also, it should have only added 2" to the height, not 4", putting it at 4.26" tall rather than 6.26".

I will have to look at this. It possibly might have ignored the returns for some reason, and I will have to look at the height disparity.

> The right wall has flat crown to the ceiling, the partition sitting 0.75" from ceiling and the top KD at the top of the partition and not down a hole (so the crown is 1" tall), left and right returns, and the front piece should be 55.50" wide and the returns 12.75" deep. Like the other wall, SNaP is showing the front piece as 55.49" instead of 55.50" for some reason.

Again, the length disparity is due to me slightly shrinking the piece in Snap to create the mitered look.

> The XML Export has 2 lengths of 6.00" tall flat crown (which is the correct number of lengths) but also there is 1 length of 5.00" tall flat crown (EDIT: there are actually 2 lengths of 5.00" tall flat crown, not just one)? Unsure what is causing that. The flat crown here should be 3.00" tall, not 6".

Again, it looks like there is a problem with the height calculation of the pieces, and I bet that returns are being accounted for differently.

**Comment by ClassyTeddy** [comment]
Ready for testing on the Flat-Crown-and-Crown-Molding-Improvements branch.

**Comment by TedClassy1209** [comment]
This still isn't quite there. Here is a job I just made:

![image](https://user-images.githubusercontent.com/61025894/99122874-5aa87180-25bc-11eb-8124-6b7839774fd7.png)

- Left wall has one length of flat crown edged all 4 and is 54x3 - That exported correctly
- Center wall is to the ceiling 4.77" tall and 120" wide - This should have 3 lengths exported at 6.77" tall edge 1L but it only had 1 length exported
- Right wall is to the ceiling 3.51" tall and 36" wide with two 12" returns - This should have 2 lengths exported (because it has returns) at 5.51" with 1L edge, but it exported 3 lengths.

![image](https://user-images.githubusercontent.com/61025894/99123377-47e26c80-25bd-11eb-8aa3-6f8cbf497001.png)

![image](https://user-images.githubusercontent.com/61025894/99123394-53ce2e80-25bd-11eb-9b38-d5765e43612d.png)

![image](https://user-images.githubusercontent.com/61025894/99123402-5761b580-25bd-11eb-9ab8-fa5dc435e9ef.png)

**Comment by TedClassy1209** [comment]
Also--it won't export an XML if you choose that a Flat Crown assembly has a left or right exposed end as well as a left or right return. It's not common, but every once in a while a design will end up with something like this where that would occur:

![image](https://user-images.githubusercontent.com/61025894/99123804-2afa6900-25be-11eb-8d72-f987fc9aee98.png)

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Flat-Crown-and-Crown-Molding-Improvements` improvements branch. Both of the issues were because of a sytax error in the code.

**Comment by ClassyTeddy** [comment]
I have noticed there is still a problem with adding inches to the height of the flat crown that I am trying to fix now.

**Comment by ClassyTeddy** [comment]
This should also now be fixed and is ready for testing on the `Flat-Crown-and-Crown-Molding-Improvements` branch.

**Comment by TedClassy1209** [comment]
This looks good to me, thanks Teddy

**Comment by TedClassy1209** [comment]
So I think I just found that this branch broke the prompt menus for light rail and valances--did that happen for you too Teddy?

**Comment by ClassyTeddy** [comment]
Yeah, it did. I think all three derive from the same file. I thought they used different prompt operators though, so I will look into the problem.

**Comment by ClassyTeddy** [comment]
Ready for testing on the Flat-Crown-And-Crown-Molding-Improvements branch.

**Comment by TedClassy1209** [comment]
Looks good to me from my tests. Now noticing some issues with the light rail XML exports but I will make that a separate issue. Thanks Teddy
