### ISSUE TITLE
Add f/b option to hutch cabinets

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#207]
Right now in https://github.com/CCDevNelson/Snap-Updates/issues/206 we are updating the ability to create hutch partitions. After we finish that, we need to add the ability to add a 3/4" f/b in the newly created hutch. The f/b should be inset and span the inside width of the outside partitions and go up to the bottom of the interior partitions/bottom KDs (or up to the bottom of a capping bottom if one is there). The option for a Hutch Back should only become available if either or both of the "Extend Left Side" or Extend Right Side" options are selected.

**Comment by ClassyTeddy** [comment]
Ready for testing on the  `Creating-Bottom-Capping-Library-Item` branch

**Comment by TEDSTANDAGE** [comment]
Good start. A couple things to address--When there is a capping bottom, instead of resizing to account for the 0.75" capping bottom the hutch back currently just moves down 0.75":

![image](https://user-images.githubusercontent.com/61025894/97309737-a5399800-181f-11eb-9188-25c543683ecb.png)

It should just take the top 0.75" off the back rather than move it down--it should still be flush with the bottom of the partition.

Next, if you add the back before you put in a capping bottom then the back and capping bottom overlap instead of the back taking the top 0.75" off to account for the capping bottom:

![image](https://user-images.githubusercontent.com/61025894/97310044-08c3c580-1820-11eb-823a-a5d7065a615f.png)

Not sure if that can be dynamic where the back would adjust to a capping bottom being placed after the back is placed.

**Comment by ClassyTeddy** [comment]
> Next, if you add the back before you put in a capping bottom then the back and capping bottom overlap instead of the back taking the top 0.75" off to account for the capping bottom:
If you make a change in the partition prompts, it will fix this. I'll try to make it work better however

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Creating-Bottom-Capping-Library-Item` branch

**Comment by TedClassy1209** [comment]
The hutch back is still sticking down 0.75" when a capping bottom is in place:

![image](https://user-images.githubusercontent.com/61025894/99316400-8e380580-2821-11eb-98ac-0a87d51b2d5e.png)

The hutch back needs to have 0.75" taken off of its height when a capping bottom is in place--the bottom of the back needs to be flush with the bottom of the hutch partitions. 

Also, the hutch back looks like it has edgebanding on the sides? Though no edgebanding info is going to the XML--A hutch back won't be exposed so it won't need edgebanding.

**Comment by ClassyTeddy** [comment]
No edge banding is going through, it just doesn't have the core material applied to it cause there is no way you would see it. We only apply that material to parts that the user might see, otherwise we don't need to.

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Creating-Bottom-Capping-Library-Item` branch

**Comment by TedClassy1209** [comment]
Looks good to me, thanks Teddy
