### ISSUE TITLE
Updated Handle Pulls

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#211]
Update handles

**Comment by SeanRadvan** [comment]
@RyanMDev I noticed that on a few of the handles, the "bases" I added to the handles are clipping into the doors, and I'm unsure how to fix it. Particularly the Satin Nickel handles 133.50.195 and 133.50.198.
![clip 3](https://user-images.githubusercontent.com/54151330/96733607-809c7680-136e-11eb-8c79-98dcc0e4dec1.jpg)
![clip 4](https://user-images.githubusercontent.com/54151330/96733623-842ffd80-136e-11eb-95fe-a7efaf9fff08.jpg)

**Comment by TEDSTANDAGE** [comment]
Sean, please identify the branch you created and are working from. Do you know the thickness of those bases? Are other handles going into the faces as well and the missing bases are just showing an already existing issue, or is it only the new handles with bases that are going into the faces? Looks like we need to adjust the location of the handles that are going into the faces, whether its just those with the bases or others as well. I think Teddy should be able to help you on creating a rule for that.

**Comment by ClassyTeddy** [comment]
So we can only change all the handles at once, not the individual one having the issue. The problem here most likely lies in the .blend file that the pull is using to show up in SNaP is not working right for whatever reason. I am not positive how those work and this is most likely a question for Ryan.

**Comment by SeanRadvan** [comment]
Oh sorry, its on the Handle-Pull branch. I don't know the thickness, they were just simple objects I drew simple objects to be a rough representation of the handle. I did speak to teddy about it yesterday, but he thought it might be a better question for Ryan. Looking at other handles that I didn't draw, there appears to be some amount of clipping, though I don't know if that's intentional, and they have extra material added to the base to make them look right.
![handle clip](https://user-images.githubusercontent.com/54151330/96741200-69fa1d80-1376-11eb-9bc6-deffe5ae8654.jpg)

**Comment by CCDevNelson** [comment]
Since this is PURELY cosmetic and has nothing to do with the drilling or construction of the cabinet, I think this is NOT something we need to worry about at the moment.

**Comment by TEDSTANDAGE** [comment]
> Since this is PURELY cosmetic and has nothing to do with the drilling or construction of the cabinet, I think this is NOT something we need to worry about at the moment.

I don't think Ryan should be spending his time on this right now as it it not a priority, but I am fine with Sean R. figuring it out if he can as he learns Blender/SNaP. So, Ryan, please keep working on the other items you are currently working on.

Sean R./Teddy, the insertion point of pulls should be based on the base of the pull, so I would double check that is how it is configuring/orienting the pulls so that it doesn't matter how deep a pull is or how much it sticks out--the location of the base of the pull (how far from the wall it is) will always be the same no matter the size of the pull (depth of pard plus thickness of the door/face).

Then Sean, I saw this issue you may have already pointed out to me that you are working on but I will document it here. We don't have .pngs for certain gold handles:

![image](https://user-images.githubusercontent.com/61025894/96743959-5e5c2600-1379-11eb-948d-2a1b901b744f.png)

But, they still appear to be rendering in the scene.

I will check the XML exports of the handles in a bit. 

Thanks, 

Ted

**Comment by TEDSTANDAGE** [comment]
Brushed Nickel doesn't look very Brushed Nickel-y in the scene:

![image](https://user-images.githubusercontent.com/61025894/97051651-63190980-1534-11eb-964d-d6ed4879d678.png)

It looks like the Satin Bronzed Copper. 

Stainless Steel also looks like Satin Bronzed Copper:

![image](https://user-images.githubusercontent.com/61025894/97052426-d8d1a500-1535-11eb-82c3-33ddbc95197b.png)

Not sure if there is a better material file we can use? Whatever we use for Chrome looks closer to nickel/steel than what is currently being used.

**Comment by TedClassy1209** [comment]
Sean, have you been able to address this? See https://github.com/CCDevNelson/SNaP-Dev/issues/263

**Comment by SeanRadvan** [comment]
I have not, i've been in the shop and getting the new pcs ready. Hoping to
have a min to look at it today.

**Comment by SeanRadvan** [comment]
Colors adjusted and moved origin point to fix cliping issue.

**Comment by TedClassy1209** [comment]
Looking good, thank you Sean. As we talked about, Satin Nickel is looking a little yellow. Let's change the metal material for satin nickel to just match the brushed nickel. 

Also we have the issue of the color of pulls in the scene changing while browsing pulls in the menu (even without selecting "Change Pull" or "Replace All"). 

These aren't priority items, but once you get the metal material changed for satin nickel then I say we push this to Ryan to get merged. Thanks, Ted

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Handle-pull` branch. 

Sean, you should take a look at the code I did. I simplified the list as well as moved the whole thing so now it is directly attached to the execute function of the `OPERATOR_Update_Pull_Selection` class in `mv_closet_defualts.py` file. 

That operator's execute function is called every time the `Update Pull` or the `Replace All` button is pressed.

I also made it so it now changes the pulls material directly, rather than use the `Pull-Finish` material pointer, which all pulls used to point to (That is why all pulls would change color when a different pull was selected, because they were all pointing to `Pull-Finish` as a reference)

**Comment by kategodfrey** [comment]
The part number 125.68.352 (oil rubbed bronze) does not have the right picture

![PDF hardware oil rubbed bronze](https://user-images.githubusercontent.com/63115502/100941672-3d7a0b00-34b7-11eb-81a7-554ead2cdd32.png)
![Snap library oil rubbed bronze 12-2](https://user-images.githubusercontent.com/63115502/100941685-44088280-34b7-11eb-8ca4-406718120c0b.png)

Also, the satin brass when rendered is too yellow.. but I can't think of a solution off the top of my head.
![Antique satin brass pdf](https://user-images.githubusercontent.com/63115502/100941992-c7c26f00-34b7-11eb-892d-4f54f4b26584.png)
![snap antique satin brass 12-2](https://user-images.githubusercontent.com/63115502/100941996-cabd5f80-34b7-11eb-83cc-a6a871a22dca.png)

**Comment by SeanRadvan** [comment]
Looking at the hafele website, they are showing the pull we currently have
at 125.68.352. Assuming our reference number is wrong, I can replace it
with the bar pull, but i would need the correct items. As for the brass, it
certainly does look a bit more yellow when rendered. I will fiddle with the
colors and try to find something more appropriate.

**Comment by TedCC1209** [comment]
Our 125.68.352 is correct in SNaP. Katie, whatever brochure you are going off of is incorrect. 

![IMG_7912](https://user-images.githubusercontent.com/61025894/101049228-904bd500-3540-11eb-892e-23afede65f8b.jpg)

**Comment by SeanRadvan** [comment]
![updated antique](https://user-images.githubusercontent.com/54151330/101074468-ff83f200-355d-11eb-8dc7-ed18b29d5c77.jpg)
I fiddled with the color on the antique satin brass. Its a fine line between brown / gold / yellow, but i think it looks pretty close. I can change it again if needed.

**Comment by SeanRadvan** [comment]
If no one has any issues it looks ready to push.
