### ISSUE TITLE
Doors: Hang Showing through in snap and in 2Ds

### ISSUE THREAD

**Issue by kategodfrey** [CCDevNelson/Snap-Updates#212]
When the doors are closed with hang behind them you cannot see that there is a hang section in the 2D views. It would be nice if they appeared in gray or dashes similar to shelves behind doors. I will attach pics below to show what I am seeing.

![2Ddoors](https://user-images.githubusercontent.com/63115502/96644780-64e98f80-12de-11eb-83ff-5790a0232c00.png)
![doors](https://user-images.githubusercontent.com/63115502/96644830-79c62300-12de-11eb-944e-d082eff62dbe.png)

**Comment by TEDSTANDAGE** [comment]
You won't do a hang section behind doors unless it is 24" deep, _maybe_ 22" deep but that is cutting it close. Hangers and clothes won't fit behind the doors otherwise.

It is an issue though that the 2D Views don't show what's behind doors because we need to see what is going on behind them. It should show a dotted line or dash lines of the objects behind the doors.

However, we do not want to see drawer boxes behind drawer faces, so the fix for seeing what is behind doors in 2D Views should not apply to drawer faces.

**Comment by AntonioGloria** [comment]
Hi @TedCC1209,
Here's the fix for this issue. 
2D Views will now show any objects that are behind doors or faces unless those objects are explicitly marked not to show in see-through views. Vertical panels, KDs, drawers, and toe kicks won't show as dashed lines. While working on this issue, I also found a fix for the glitch highlighted in this comment: https://github.com/CCDevNelson/Snap-Updates/issues/242#issuecomment-752197176
![github_sample](https://user-images.githubusercontent.com/74732175/104040428-3f617900-519d-11eb-8a8f-73804ffe1a5c.png)
![custom_sample](https://user-images.githubusercontent.com/74732175/104040423-3e304c00-519d-11eb-807b-958a09731ca2.png)
The fix is located here: https://github.com/nailsonlandim/SNaP-Dev/tree/3DLabels

**Comment by TedCC1209** [comment]
Thanks @AntonioGloria! Great start and glad you found a fix for the issue pointed out in the comments of 242.

An initial question--does it differentiate between a top/bottom KD and a middle KD? There are times there will be a KD (or KDs) that is/are not at the top or bottom of the door that we would want to show up as a dotted line behind the doors.

**Comment by AntonioGloria** [comment]
At the moment it doesn't differentiate KD placements, it just identifies whether the shelves are locked.

**Comment by TedCC1209** [comment]
> At the moment it doesn't differentiate KD placements, it just identifies whether the shelves are locked.

Okay, let's take out KDs as an excepted item for now then if you can, until we can differentiate between the KDs we want dotted lines for and those we don't. It'll be better to have a dotted line at the top and bottom of a door/drawer face if it means we can see middle KDs as well.

**Comment by AntonioGloria** [comment]
Got it. I have removed KDs from the exceptions for the time being.
![KDs_Included](https://user-images.githubusercontent.com/74732175/104070157-d47b6680-51cb-11eb-9f64-579856ec42d3.png)
The latest version of this fix is here: https://github.com/nailsonlandim/SNaP-Dev/tree/3DLabels

**Comment by AntonioGloria** [comment]
Hi @TedCC1209 and @kategodfrey,

The 2D views dashed lines now only exclude top and bottom KDs while showing other KDs.
![github_sample](https://user-images.githubusercontent.com/74732175/104662926-71894400-5691-11eb-9eae-79de4fda5c7d.png)
![custom_sample](https://user-images.githubusercontent.com/74732175/104662924-6e8e5380-5691-11eb-84a7-84047ff21c37.png)

The latest version of this fix is here: https://github.com/nailsonlandim/SNaP-Dev/tree/3DLabels
