### ISSUE TITLE
Custom Partition Depth option

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#221]
We need to add a custom partition depth option in the construction options of partitions where we can change the depth of a single partition without changing the drilling or the adjacent section depth(s). This happens in rare but still-sometimes-occurring situations--for example, like certain types of hutches or to cover the otherwise exposed wall of a wrap around corner area.

**Comment by TedCC1209** [comment]
The left end and right end deduction option essentially does this already but we shouldn't allow it to be set back--it should only be able to be brought forward. I want to ensure the drilling on this is correct, so let's look at it together when you get to this issue.

**Comment by TedCC1209** [comment]
1. Change existing "Extend Left Side" and "Extend Right Side" prompts to say "Extend Left Side Down" and "Extend Right Side Down", respectively
2. Change "Left End Deduction" and "Right End Deduction" prompts to say "Extend Left Side Forward" and "Extend Right Side Forward", respectively.
3. Change "Extend Left Side Forward" and "Extend Right Side Forward" so that positive numbers means it is being extended (currently with it being a "Deduction" you have to do a negative number to add depth to the partition), and only allow positive numbers, we don't want to deduct.
4. Change "Extend Left Side Forward" and "Extend Right Side Forward" to be buttons just like "Extend Left Side Down" and "Extend Right Side Down" currently are, with the prompt asking for the actual distance to pop up after the button is selected (exactly how "Extend Left Side Down" and "Extend Right Side Down" currently works).

**Comment by ClassyTeddy** [comment]
So, for the first issue, all you would need to do is change the name of the prompts, and make sure that all the variables reference the new names. "Extend Left Side" and "Extend Right Side" are found on line 30 and 31 of the `common_prompts.py` file. Once you change the name of the prompt, you then have to go into `data_closet_carcass.py` and change every reference to the old name to now match the new name.

Issue 2 would be exactly the same as issue 1, except issue 4 changes how we want that prompt to function, so let's tackle that first.

To solve issue 4, we first need to add 2 new prompts. We are going to add 2 checkbox prompts that are above the prompts "Left End Deduction" and "Right End Deduction" found starting at line 12 of `common_prompts.py`. These new prompts should be named "Extend Left Side Forward" and "Extend Right Side Forward", the `prompt_type` should be 'CHECKBOX', the value should be `False` and the `tab_index` should be 1
Then, you need to change "Left End Deduction" and "Right End Deduction" to "Extend Left Side Forward Amount" and "Extend Right Side Forward Amount", and change all the variables that reference those names in `data_closet_caracass.py`
Then, in order to mimic how "Extend Left Side" and "Extend Right Side" currently work in the prompts menu, remove lines 2594 and 2597, then copy 2599 to 2613, changing `extend_left_side` to `extend_left_side_forward`, `extend_right_side` to `extend_right_side_forward`, `height_left_side` to `extend_left_side_forward_amount`, and `height_right_side` to `extend_right_side_forward_amount`

For the first part of issue 3, you need to change lines 255, 263, 296, and 304 in the `data_closet_carcass.py` file so that "Extend Left Side Forward Amount" and "Extend Right Side Forward Amount" now move the partition forward when given a positive value. 
For the second part of issue 3, you need to add an if statement in the `check` function found on line 1794 that checks to see if "Extend Left Side Forward Amount" and "Extend Right Side Forward Amount" equal a negative amount. If they do equal a negative amount, set their values to 0.

Let me know if you have any questions or run into any issues @JJanneh

**Comment by JJanneh** [comment]
![Extend Left  Right Side Ammount](https://user-images.githubusercontent.com/76751383/103587585-d203ce80-4ea4-11eb-8a23-df8ea1fe3f40.png)

**Comment by JJanneh** [comment]
![LSide_Down](https://user-images.githubusercontent.com/76751383/103685124-e8179a80-4f49-11eb-8c79-576b4aec78b2.PNG)
updated

**Comment by JJanneh** [comment]
Custom_Partition_Depth Branch Testing

**Comment by ClassyTeddy** [comment]
Hey @JJanneh 

So what you have on the `Custom_Part_Depth` branch is a good start, but you only really have one step of what needs to be done ready. 

So you had asked me how to not allow negative numbers in an email, and in order to do that, you need to do this:
> For the second part of issue 3, you need to add an if statement in the check function found on line 1794 that checks to see if "Extend Left Side Forward Amount" and "Extend Right Side Forward Amount" equal a negative amount. If they do equal a negative amount, set their values to 0.

Basically, what this means, is that inside of the `check` function found at line 1794, you need to check and see if the prompts equal a negative value. To do that, you would want to do something like this

```python
extend_left_side_amount = self.product.get_prompt("Extend Left Side Amount")
extend_right_side_amount = self.product.get_prompt("Extend Right Side Amount")

if extend_left_side_amount and extend_right_side_amount:
    if extend_left_side_amount.value() < 0:
        extend_left_side_amount.set_value(0)
    if extend_right_side_amount.value() < 0:
        extend_right_side_amount.set_value(0)
```

So, the first two lines retrieve the prompts and sets them equal to a variable. If the prompts do not exist (Either they weren't added, it is an older part that doesn't have them, or more often there is a spelling error), then the `.get_prompt()` function will return `None`

Then, the next line of code checks to see if the prompt exist. This is **VERY** important! If you try to use the `.value()` or the `.set_value()` on a prompt that doesn't exist (i.e. `None`), then the code will return an error and stop whatever it was in the process of doing. 

If the prompts in question do exist, then it checks to see if the value of the prompt is less than 0. If it is, then it sets the value of the prompt to 0. 

Let me know if that makes sense, or if you need further clarification.

**Comment by JJanneh** [comment]
This makes sense. But from my understanding Change "Extend Left Side Forward" and "Extend Right Side Forward" so that **positive numbers means it is being extended** (currently with it being a "Deduction" you have to do a negative number to add depth to the partition), and only allow positive numbers, we don't want to deduct.
 
I placed the code inside check function found at line 1794. That example i tried several times. After code insertion it seems to brake SNaP and doesn't seem to fix the Negative number issue . **Negative** numbers increase the size and **Positive** reduce the size.

I need to Reverse this action So **Positive Numbers Increase** the Size. And Completely remove the Negative option completely.  Will continue to troubleshoot. 
![Ext_LT Ext_RT_Deduction](https://user-images.githubusercontent.com/76751383/103823685-cc86bf80-502f-11eb-982c-19da62b4f72a.png)

**Comment by ClassyTeddy** [comment]
Ah, I just thought you hadn't gotten to that part.

>For the first part of issue 3, you need to change lines 255, 263, 296, and 304 in the data_closet_carcass.py file so that "Extend Left Side Forward Amount" and "Extend Right Side Forward Amount" now move the partition forward when given a positive value.

So, at lines 255, 263, 296, and 304, you will find that the `.y_dim` of the left and right partitions and the `.y_loc` of the left and right fillers are being manipulated using the variables "Left_End_Deduction" and "Right_End_Deduction". Theses variables are created using the ".get_var()" function on lines 220 and 221. You need to change the driver functions of the `left_filler`, `left_side`, `right_filler`, and `right_side` to now increase with a positive value, rather than decrease.

Here is an example for what you need to do using the `left_side.y_dim`

What it currently is:
```python
left_side.y_dim('-Depth_1+Left_End_Deduction',[Depth_1,Left_End_Deduction])
```

What it needs to be:
```python
left_side.y_dim('-Depth_1-Extend_Left_Side_Forward',[Depth_1,Extend_Left_Side_Forward])
```

Let me know if that makes sense. I do apologize, I thought that you just hadn't gotten to that step in my above instructions.

**Comment by JJanneh** [comment]
Tried this it breaks.
So, at lines 255, 263, 296, and 304, you will find that the .y_dim of the left and right partitions and the .y_loc of the left and right fillers are being manipulated using the variables "Left_End_Deduction" and "Right_End_Deduction". Theses variables are created using the ".get_var()" function on lines 220 and 221. You need to change the driver functions of the left_filler, left_side, right_filler, and right_side to now increase with a positive value, rather than decrease.

Here is an example for what you need to do using the left_side.y_dim
@ClassyTeddy

**Comment by ClassyTeddy** [comment]
Can you show me how it breaks?

**Comment by JJanneh** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/76751383/104243279-937a9080-541d-11eb-8b7d-14b78f41524f.png)
I had to revert changes @ClassyTeddy

**Comment by ClassyTeddy** [comment]
So the error message is that `self_var` is not defined, which it isn't. It then shows you the line where it encountered an error and stopped, which is line 220 in `data_closet_carcass.py`.
The line creating the error is:
```python
Extend_Left_Side_Forward = self_var("Extend Left Side Forward")
```

What the line should be is this:
```python
Extend_Left_Side_Forward = self.get_var("Extend Left Side Forward")
```

`self` is referring to the assembly itself, and `get_var` is a function that can be called on assemblies that retrieves the given prompt (Which in this case is `"Extend Left Side Forward"`) as a variable that can be used in the driver functions like `.y_loc` and `.y_dim`

So you need to change that line to have the correct syntax (and possibly others) and see what happens next.

**Comment by JJanneh** [comment]
@ClassyTeddy 
![Screenshot (44)](https://user-images.githubusercontent.com/76751383/104330933-bf445780-54ab-11eb-8866-f6961f4f15a6.png)
The Changes worked but the UI in SNap looks like this..

**Comment by JJanneh** [comment]
[image: Ext_LT&Ext_RT_Deduction.png]

**Comment by ClassyTeddy** [comment]
Alright so, when a piece comes put really thin like that, that means there is a driver error, and it decides to just calculate to 0. Can you send the 4 lines you changed so I can see what might be causing the error?

**Comment by JJanneh** [comment]
File location **data_closet_carcass.py**
Lines Below
**255**- left_filler.y_loc("-Depth_1+Left_End_Deduction", [Depth_1, Left_End_Deduction])
**263**-left_side.y_dim('-Depth_1+Left_End_Deduction',[Depth_1,Left_End_Deduction])
**296**-right_filler.y_loc("-Last_Depth+Right_End_Deduction", [Last_Depth, Right_End_Deduction])
**304**-right_side.y_dim('-Last_Depth+Right_End_Deduction',[Last_Depth,Right_End_Deduction])

**Comment by JJanneh** [comment]
![Screenshot (97)](https://user-images.githubusercontent.com/76751383/105226208-f1456180-5b1c-11eb-97c3-404032889abb.png)

**Comment by TedCC1209** [comment]
Thanks J, looks good. Now that I am seeing it I think the right wording would be "Extend Left End Pard Forward", "Extend Right End Pard Forward", "Extend Left End Pard Down", and "Extend Right End Pard Down" (I would prefer to say Partition instead of Pard, but it is already long enough).

When you change that wording will this be ready for testing? Let me know the name of the branch you are working on for this and I will take a look.

**Comment by JJanneh** [comment]
Changing names and functions now. Testing Pop up feature in progress for the Extend L/R End Forward Current branch Custom_Partition_Depth
![Pard_](https://user-images.githubusercontent.com/76751383/105232229-4eddac00-5b25-11eb-85c4-7a2e58dc39fb.PNG)

**Comment by TedCC1209** [comment]
Thank you J.

@ClassyTeddy is there a particular reason you had the L/R end extension down be a button first and then the second popup have it ask the amount?

**Comment by ClassyTeddy** [comment]
I don't believe so. It does make the logic for the hutch easier, but the logic could be changed

**Comment by JJanneh** [comment]
![Screenshot (100)](https://user-images.githubusercontent.com/76751383/105384491-830da700-5bcf-11eb-92b8-5e2bbb0621f3.png)

**Comment by TedCC1209** [comment]
@kategodfrey @sarahhightower please take a look at how the forward & down extensions look and work in the prompt menus and let me know your thoughts on its user friendliness (call or email me please). Thanks, Ted

**Comment by TedCC1209** [comment]
Okay let's keep it like this J, thank you. Let's change the wording of the prompt to enter the extension amounts to the following:

![Wording](https://user-images.githubusercontent.com/61025894/105405408-5ca83580-5be8-11eb-8891-d2efa12dc02a.png)

**Comment by JJanneh** [comment]
Change the wording requested.
![Wording of the prompt](https://user-images.githubusercontent.com/76751383/105408343-10f78b00-5bec-11eb-9c72-732093db2a9a.PNG)

**Comment by JJanneh** [comment]
Custom_Partition_Depth Branch ready to test Prompt functions
![Screenshot (105)](https://user-images.githubusercontent.com/76751383/105733575-f163a980-5eee-11eb-95ce-37cd4f8e27d6.png)

**Comment by JJanneh** [comment]
Ready to Test Custom_Partition_Depth

**Comment by sarahhightower** [comment]
Looks good! I just notice one small thing that isn't consistent. When you click on "Extend left end pard forward" or "Extend left end pard down" the fields below appear for those left options only. But, when you click on "Extend right end pard forward" or "Extend right end pard down" the fields appear for both the left and right side, even if the left sides don't have checkmarks. Visuals included to make this clear....

![1](https://user-images.githubusercontent.com/72047269/106181847-50c5f180-615b-11eb-9579-50352f937227.png)

![2](https://user-images.githubusercontent.com/72047269/106181860-53284b80-615b-11eb-97e5-839bead54357.png)

**Comment by TedCC1209** [comment]
> Looks good! I just notice one small thing that isn't consistent. When you click on "Extend left end pard forward" or "Extend left end pard down" the fields below appear for those left options only. But, when you click on "Extend right end pard forward" or "Extend right end pard down" the fields appear for both the left and right side, even if the left sides don't have checkmarks. Visuals included to make this clear....

Good catch @sarahhightower . Along with fixing what @sarahhightower pointed out @JJanneh , please have the rows for the fields where you put the extension amounts show up directly under the row of the check box that is selected rather than showing up all the way below the row for "Add Hutch Backing".

Thanks, Ted

**Comment by JJanneh** [comment]
Ok making adjustments now. Extension amounts show up directly under the row
of the check box that is selected.

**Comment by JJanneh** [comment]
Changed extension amounts show up directly under the row of the check box that is selected

**Comment by JJanneh** [comment]
![Screenshot (115)](https://user-images.githubusercontent.com/76751383/106198828-c50b8f80-6171-11eb-8e23-398ee0435800.png)

**Comment by TedCC1209** [comment]
@JJanneh is this branch good to test with the latest updates? I need to focus on testing the drilling/machining aspect of this to make sure the front line of holes isn't moving with the front of the partition when it gets extended. Thanks, Ted

**Comment by JJanneh** [comment]
This branch has the current SNaP updates 1.2.4

**Comment by TylerStandage** [comment]
The functionality is there per the UI, but the lines for left/right pard forward are still showing up under the filler check boxes. 

@TedCC1209 if you can help point me to where the drilling shows up in the xml, I'll take a look... having a tough time finding it. 

![Capture221](https://user-images.githubusercontent.com/77167318/107684000-18440e80-6c57-11eb-9dc1-9d6297d50799.PNG)

**Comment by JJanneh** [comment]
Try Custom_Partition_Depth branch ![Screenshot (269)](https://user-images.githubusercontent.com/76751383/107684724-57c32880-6c60-11eb-9638-982c8865e262.png)

**Comment by TedCC1209** [comment]
> The functionality is there per the UI, but the lines for left/right pard forward are still showing up under the filler check boxes.
> 
> @TedCC1209 if you can help point me to where the drilling shows up in the xml, I'll take a look... having a tough time finding it.

It is really hard to really tell how drilling is just by looking at the XML in an XML viewer, it lists the coordinates of every single hole under Manufacturing > Operation Groups. 

Here are directions for getting to Drilling Debug Mode:

1. Enable the debug mode in your User Preferences. To do this, Press `CTRL+ALT+U` to open your user preferences. Then, navigate to the `Add-Ons` tab. Scroll down until you see a selected option labeled `Snap:Snap`. Open that option, and then enable and open `Snap Advanced Options'. After that, enable the `Debug Mode` and save user settings in the bottom right corner. 

2. Close and Restart Snap.

After reopening Snap, you should notice that you have a new tab in your toolbar labeled `Closet Machining Setup`. If you do not, try the above steps again.

3. Open a room.

4. Save the room, either by opening `File` in the top left corner and then clicking `Save`, or by hitting `CTRL+S` then selecting the option saying that it is ok to save over the room.

5. Export the Room/Project.

IMPORTANT: DO NOT SAVE THE ROOM AGAIN AFTER EXPORTING

6. Reopen the room.

Note: it is now safe to save the room again if need be. 

7. Now, open the tab labeled `Closet Machining setup. In there, you will find a couple of options for your drilling (don't change those), as well as a list of items. The first item in the list will be labeled `Main` and the rest will be labeled after different parts in the scene. The names of the parts will include the `IDP-#`, which can be cross referenced with the XML. 

8. Click on one of the items in the list. This will open a new scene with a wire frame of the part in front of you. Here, you can see where the drilling on this particular part is. These displayed holes use the information found in the XML to display the holes. 

I haven't had the time to use this yet on this, or checking on things like the 3 lines of holes.

**Comment by JJanneh** [comment]
Updated and Ready to test.
![Screenshot (276)](https://user-images.githubusercontent.com/76751383/107777242-cd320600-6cff-11eb-88e4-fb6c8fe54688.png)

**Comment by TedCC1209** [comment]
﻿Thanks J, can you switch the order of the left and right extension amount rows so that left is first? Generally, things should go left to right. Thanks, Ted

**Comment by JJanneh** [comment]
Yes. Thanks Ted Here is the change Left to Right Checkbox Selection ![Left to Right](https://user-images.githubusercontent.com/76751383/107787253-14be8f00-6d0c-11eb-89c2-b161d60678de.PNG)

**Comment by sarahhightower** [comment]
Looking good. A few things I noticed.  

1) The "Left Filler Setback Amount" and "Right Filler Setback Amount" appear before selecting "Add Left Filler" or "Add Right Filler". This prompt would not be used unless there is filler so it might work best if it doesn't appear until the filler option is selected.

2) There's a bit of inconsistency with the boxes that appear after putting checkmarks in their option fields. For example, "Left Filler Setback Amount" and "Right Filler Setback Amount" each have half length boxes no matter what. But when you select "Add Left Filler" the box extends the full length of the prompt. Then when the "Add Right Filler" box is selected all of the fields have half length boxes again. The left and right extend pards down and forward boxes are always full length boxes. 

Personally, I like the half length boxes that appear directly until the corresponding left or right side prompts. Open to hear if @TylerStandage feels it is necessary to make consistent or not.

![1](https://user-images.githubusercontent.com/72047269/107791154-d4154480-6d10-11eb-85d2-d1480f31bda7.png)

![2](https://user-images.githubusercontent.com/72047269/107791170-d7103500-6d10-11eb-9840-adaf3e22dea9.png)

![3](https://user-images.githubusercontent.com/72047269/107791180-d9728f00-6d10-11eb-8cc2-e276d6caa4cd.png)

**Comment by TylerStandage** [comment]
@JJanneh @sarahhightower I agree that we should be consistent in the half length fields for fillers and pard changes, and that we should be consistent in when those fields appear.  Not having them appear until the box is checked makes sense to me.

So J, let's update all of those to be consistent. I think you said you were going to ask @ClassyTeddy how to have the fields go half way vs the full length. Perhaps that's something we can cover in the 1pm meeting on Monday?

It also looks like the XML is not extracting, so it is likely the drilling is being changed, which we don't want. @TedCC1209, do you have a suggestion on next steps for this issue?

**Comment by JJanneh** [comment]
Checkbox prompts Left to Right
![Checkbox Size Reduced 2](https://user-images.githubusercontent.com/76751383/107822038-b230b780-6d3a-11eb-918d-6d752e27e357.PNG)![Checkbox Size Reduced](https://user-images.githubusercontent.com/76751383/107821952-8e6d7180-6d3a-11eb-98d4-313335d8a80f.PNG)

**Comment by sarahhightower** [comment]
Awesome. Thanks for figuring that out @JJanneh!

Just something I noticed from your screenshot..."Add Capping Right Filler" appears both on the left and right side.

**Comment by JJanneh** [comment]
Thanks @sarahhightower Changes made.
![Capping_Filler LR](https://user-images.githubusercontent.com/76751383/107825919-31c18500-6d41-11eb-89b4-6555b85690f3.PNG)

**Comment by TylerStandage** [comment]
Good eye, @sarahhightower and thanks @JJanneh. Looks like that part of this issue is resolved. Here is a summary of what I believe still needs to be done on this one:

1. for the extend forward and down options, have the fields take up only half the prompt window (may need to consult with Teddy on how to do this)
2. Fix the requirement for "extend right pard forward" box to be checked for the "extend down" boxes to show on the screen 
3. Confirm whether there are errors leading to no XML file being created. @TedCC1209 will confirm this and create separate issue once it's understood better.

**Comment by TedCC1209** [comment]
> 3. Confirm whether there are errors leading to no XML file being created. @TedCC1209 will confirm this and create separate issue once it's understood better.

XML files are being created if I am not in Debug Mode. If I am in Debug Mode then I get the following error:

> load_materials_from_db Finished: 1.7411 sec
> Error: Traceback (most recent call last):
>   File "C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\addons\snap_db\snap_export.py", line 3210, in execute
>     self.debugger = debug_xml_export.Debug()
> NameError: name 'debug_xml_export' is not defined
> 
> location: C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\modules\bpy\ops.py:187
> 
> Traceback (most recent call last):
>   File "C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\addons\snap_db\snap_export.py", line 3210, in execute
>     self.debugger = debug_xml_export.Debug()
> NameError: name 'debug_xml_export' is not defined
> 
> location: C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\modules\bpy\ops.py:187
> 
> location: C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\modules\bpy\ops.py:187
> Error: Traceback (most recent call last):
>   File "C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\addons\snap_db\snap_export.py", line 3210, in execute
>     self.debugger = debug_xml_export.Debug()
> NameError: name 'debug_xml_export' is not defined
> 
> location: C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\modules\bpy\ops.py:187
> 
> Traceback (most recent call last):
>   File "<string>", line 2, in <module>
>   File "C:\Users\teds\AppData\Local\Temp\blender_a07780\export_temp.py", line 2, in <module>
>     bpy.ops.snap_db.export_xml('INVOKE_DEFAULT', xml_path='C:/Users/teds/Documents/SNaP Projects/101 test')
>   File "C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\modules\bpy\ops.py", line 187, in __call__
>     ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
> RuntimeError: Error: Traceback (most recent call last):
>   File "C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\addons\snap_db\snap_export.py", line 3210, in execute
>     self.debugger = debug_xml_export.Debug()
> NameError: name 'debug_xml_export' is not defined
> 
> location: C:\Users\teds\Documents\GitHub\SNaP-Dev\SNaP\2.78\scripts\modules\bpy\ops.py:187
> 
> 
> 
> Blender quit
> 

It is only in this branch that I have seen that I can't get an XML to export while in debug mode (I can export in debug mode on other branches), it is different than the issue in https://github.com/CCDevNelson/Snap-Updates/issues/307. I would think we would want to address this within this branch/issue since I am only seeing it occur here. If we are seeing it in other instances then it would make more sense to me to make it a separate issue.

**Comment by JJanneh** [comment]
@TylerStandage @TedCC1209 The extend forward and down options, have the fields take up only half the prompt window
Fix the requirement for "extend right pard forward" box to be checked for the "extend down" boxes to show on the screen
Updated the Export file to current Confirmed whether the XML file being created.  ![Export Output](https://user-images.githubusercontent.com/76751383/107994677-5c5a4a80-6f9a-11eb-9ba3-c82f182d420d.PNG)
![UI Changes](https://user-images.githubusercontent.com/76751383/107994713-67ad7600-6f9a-11eb-9be9-67a86f1a4b40.PNG)

**Comment by TylerStandage** [comment]
@JJanneh this one is good to merge, thanks! 

@ClassyTeddy for reference/reminder when merging: #221 and #288 are on the topshelf-covering-filler branch, as are the correct menu subtitles as requested by Ted. #272 and #253 are on the option to-edge-bottom-edge branch. #271 is  on its own branch.
