### ISSUE TITLE
Room category required.

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#244]
When testing room category, even though it says its required you can just click OK and it will still create the room afterwards. If it passes any information then we should probably make it so the user cant continue without selecting a room type.
![image](https://user-images.githubusercontent.com/54151330/102803664-d513a080-4375-11eb-88d8-90e270f75459.png)
![Required2](https://user-images.githubusercontent.com/54151330/102803718-eeb4e800-4375-11eb-842a-89d299091ff1.jpg)

**Comment by TedCC1209** [comment]
@ClassyTeddy are you able to restrict the user from hitting "Ok" until they make a selection?

The user will learn will quick not to just hit Ok since that means they cannot make adjustments to the room dimensions if they do that, but then they will have to delete the room and re-make the room--which will cause further issues if they delete the room then create another room in the same project with the same room name. So, it'd be nice to just avoid this inevitable problem by not allowing them to hit "Ok" until a selection is made.

**Comment by ClassyTeddy** [comment]
I couldn't find a way to force the user to select a category, this is unfortunately the best option. It will pass on information that no room category was selected when the user exports to XML. I also prefer this solution as it makes testing faster not having to pick a category.

**Comment by ClassyTeddy** [comment]
> @ClassyTeddy are you able to restrict the user from hitting "Ok" until they make a selection?
As far as I know, there is no way to restrict the user from clicking any button. I also pursued the option of creating a new popup if the user selects OK without filling the fields out, but that also isn't possible. I spent a lot of time on this one, but I could not figure out how to force a selection.

**Comment by TedCC1209** [comment]
Okay, for now I think it'll be okay. I've been messing around with creating rooms clicking Ok before selecting a category, deleting the room by selecting the X, and then creating a new room with the same name afterward and I'm not running into any issues.

@SeanRadvan this will just be a known potential thing you may get questions on. 
@kategodfrey this will be good to include in the SNaP newsletter with/after the update so that users are aware they must select a category in order to change the room dimensions.

**Comment by TedCC1209** [comment]
@CCDevNelson does this break the XML if a category is not selected? Here is what the XML looks like when you don't put a category (I named the room "No Category Room"):

![Category Break](https://user-images.githubusercontent.com/61025894/102808320-65a1af00-437d-11eb-82d5-093d32a5dc4a.png)

Here is the XML from the above job:

https://drive.google.com/file/d/102YH1T11ZMxNRP6w6zKXiJqIV4DYEj3s/view?usp=sharing

Thanks, 

Ted

**Comment by CCDevNelson** [comment]
Ted, I thought this was going to be a drop-down list that they are required to select a category? As far as the XML goes, yes, this would cause us problems on this end since this is a required field that BC needs. If we "wait" till the point-in-time that the XML is read into production, it will make for a mess. I can check for that field to be something it's not suppose to be, but then we would have to somehow send a notice to the Designer that they forgot to select that, then remove that XML, have them send in another XML, etc..
I would think we need to verify that on the XML export function and deal with it right then. That would be my suggestion...

**Comment by ClassyTeddy** [comment]
> I would think we need to verify that on the XML export function and deal with it right then. That would be my suggestion...

This might be a possible solution, but this is probably an issue that @RyanMDev will need to solve.

There are multiple problems to this issue. 

For one, at the time, the only way I could find to save a rooms category to was to append it onto the name of the rooms file at room creation. The reason for this was due to the fact that the value of the `Room Category Property` is saved across SNaP. So when you start SNaP, the value of the Room Category Property starts as it's default, which is `REQUIRED`. If you were to create a room and change the value to let's say `Closet`, now the value of the `Room Category Property` is `Closet`. If you were to then create another room, the drop down option starts at `Closet` because that is the value of the `Room Category Property` that is saved to memory. Because of this, I cannot just retrieve the value of `Room Category Property` on export, as it's value isn't determined by what room is currently selected, but rather is determined by whatever category that was LAST selected. That is basically why the Room Category must be determined at Room Creation

The second issue is trying to force the user to pick the room category. A couple of proposed ideas were greying out or removing the `OK` button, or creating another popup when the user tries to create a room without a category. Both of these solutions cannot be used because of how the Blender `Draw` function works. The `Draw` function is what creates on screen elements in Blender. This includes popups. Because it is a default function, I have found that there are things about it you cannot change, such as not being able to remove the `OK` button. You also cannot have a `Draw` function inside of another `Draw` function, which would be the way to create popups. There still might be a solution here that I am not aware of, as I am in no way an expert on Blender, but I do not know if it is possible.

A third possible solution would be to have the user pick a room category on export, which it IS probably possible to have a popup come up when the user exports, asking them to pick a room category if they haven't already. But this runs into a similar problem as the second issue because there is still no way (as far as I know) to force the user to make a selection. They can still just click `OK`.

I spent a good while trying to find a way to force the user to select a category at room creation, and not allowing the user to change the dimensions of the room without selecting a category was the best solution I could come up with.

I do believe I also spoke to Ryan about possible solutions but, neither of us found a solution at the time.

I eventually decided on what is currently in place and I thought it was given the go ahead. If this is not an acceptable, it may need to be removed from the update. But I still think it is currently the best solution possible, as it still semi forces designers to select a room category, in order to actually pick the dimensions of the room.

@RyanMDev Your input on this issue would be appreciated, if I missed or misunderstood something, please let us know.

**Comment by TedCC1209** [comment]
> Ted, I thought this was going to be a drop-down list that they are required to select a category? As far as the XML goes, yes, this would cause us problems on this end since this is a required field that BC needs. If we "wait" till the point-in-time that the XML is read into production, it will make for a mess. I can check for that field to be something it's not suppose to be, but then we would have to somehow send a notice to the Designer that they forgot to select that, then remove that XML, have them send in another XML, etc..
> I would think we need to verify that on the XML export function and deal with it right then. That would be my suggestion...

There is a drop down list that has all the current categories and in order for the user to change the dimensions of a room (other than a Custom Room) they have to choose a category to get that option--as seen in the OP it very clearly says REQUIRED to choose a category and it is right where the user is going to be looking (https://github.com/CCDevNelson/Snap-Updates/issues/130). Unfortunately right now we are unable to disable the Ok button prior to choosing a category, so technically a user could click Ok without choosing a category, but that also means they would end up with a room that has the default dimensions (except for custom rooms which have no default dimensions) and they would likely go back and delete the room and recreate it anyway. 

I think the chances of us getting rooms without a category selected are very slim due to the above, and if we do, manually changing the room category in the XML from "No Category Found:Please Select" to the correct category wouldn't be the hardest thing. The name of the Blend file wouldn't be able to be changed though (they now include the room category number at the beginning of the name) and we can't change a category after a room is created/added to a project--we can't even rename rooms at this point after it is created (https://github.com/CCDevNelson/Snap-Updates/issues/92). So, if we denied the XML at the get-go, the designer would have to create a new room and redraw the entire thing. While that may be a quick learning opportunity for the designer never to forget it again if they have to redraw it, I think manually changing the category in the XML would be easier than re-drawing, or just reading the above category named "No Category Found:Please Select" as being "Uncategorized" or something similar. 

Again though, I believe the amount of times that will happen will be slim (until we can get a different fix in there). For now and for this update, I think we are okay but we should definitely still be working on this (maybe @thedigitalzorn can think of something while he is working on the build for the new Room Builder).

**Comment by RyanMDev** [comment]
Please test the solution found on commit: CCDevNelson/SNaP-Dev@fbe22c0bcb37b35bd99dfffd1c4e7d25fd1bcf1e

This ensures that a room will **never** be created if the room category has not been selected. 

Now if a user clicks "Ok" without selecting a room category, a message will be shown alerting the user that no room will be created because they did not select a room category.

This should bypass any issue with an incorrect XML created for a room since rooms cannot be created without a valid room category selection in the first place.

However the ability to change the category after room creation still needs to be implemented.

**Comment by RyanMDev** [comment]
@ClassyTeddy  You will also notice that I have added a message box operator in order to alert the user that they have not selected a category (commit: CCDevNelson/SNaP-Dev@f952013df55ad9832eafef86c2ade7ff7fc4373d).

You are correct here:


>  You also cannot have a `Draw` function inside of another `Draw` function, which would be the way to create popups inside of popus.

However you can call another operator with its own `draw` function. Which is what I have done here.

**Comment by TedCC1209** [comment]
This looks good to me, thanks for figuring out an initial solution Ryan

**Comment by SeanRadvan** [comment]
Looks great, this should prevent a ton of end user error.
