### ISSUE TITLE
2D Views: Make FB and partition height labels darker

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#248]
Right now the FB and partitions height labels are light gray--we end up making copies of plans for various departments so we are worried this light font won't copy well. Can we make these labels darker? Black or a darker gray is fine.

Thanks, 

Ted

**Comment by TedCC1209** [comment]
@AntonioGloria @nailsonlandim can you all work on this today by chance?

**Comment by AntonioGloria** [comment]
Hi Ted
I can take a look at this issue today.

**Comment by AntonioGloria** [comment]
Hi @TedCC1209,
Here's the fix to this issue. I'll post here the screenshots I shared with you before.

Before:
![248_Labels_Before](https://user-images.githubusercontent.com/74732175/103316909-8c9c5880-49ef-11eb-87ce-70217e210055.png)

Now:
![248_Labels_After](https://user-images.githubusercontent.com/74732175/103316941-ab025400-49ef-11eb-91b1-cc8816a55fd3.png)

The fix is available here: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23248-fb-partition-height-labels-darker
