### ISSUE TITLE
2D Views: Accounting for CT thickness in build height

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#255]
This issue stems from a comment made by @sarahhightower in https://github.com/CCDevNelson/Snap-Updates/issues/241:

> Countertop labels look good. A couple other things I noticed while running this test;
> 
> Test 1:
> 
> I used the countertop prompts to change the countertop selection for each area. I chose to do HPL on wall A, Melamine on wall B, and Granite on wall C. The drawer section with the melamine counter incorrectly notes it's height 41.91". A 4.39" toe kick was used in the design so the area with the melamine counter should be 41.16". Also, the countertops all say that they are oxford white so I decided to run a second test.
> 
> Test 2:
> 
> I cleared the 2d views, saved the file and then opened it back up. Then, I used the countertop prompts to change the countertops on wall A and C to granite, and kept wall Bs countertop melamine. Then, in the "countertop selection" of "closet materials" I chose nordic black granite. Despite changing the prompt and the countertop selection it kept my original countertop selections of test 1. Possibly the challenge here is having different countertops but this is a possible scenario. Example; a bench could have different material than a dresser countertop.
> 
> [Test 1 - 2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5736133/Test.1.-.2D.Views.pdf)
> 
> [Test 2 - 2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5736135/Test.2.-.2D.Views.pdf)
> 
> ![Test 2 Screenshot](https://user-images.githubusercontent.com/72047269/103016770-d07af380-44ff-11eb-9c35-7c13d9953e28.png)

My response was as follows: The build height issue is something you [@nailsonlandim]and @AntonioGloria should be able to address I believe--it just looks like it accounted for a 1.5" thick CT for both melamine and HPL/granite tops when it should have just been 0.75" for the melamine CT (the 41.91" build height for her job is correct for the HPL and Granite, just not the melamine). Not sure what the logic you all have in there currently, but it should account for different types of countertops within the same room--the XML and the renderings correctly show the melamine CT as 0.75" thick and the HPL & Granite as 1.5" thick.

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 @sarahhightower 

Fixed, now Build Height on countertop dimensions shows the correct value. 

I was getting the ctop thickness from the Insert instead of the cutpart itself.

Available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23241-exp-annotation-hash-mark

**Comment by TedCC1209** [comment]
It still is calculating 1.5" for the countertop if I have granite selected for countertops in the Closet Materials menu, even if I have Melamine selected for a particular countertop.

[2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5749000/2D.Views.pdf)

(Wall A has a 4.39" tk space, 36.02" pards, and a 0.75" thick melamine top - the build height should show 41.16", not 41.91")
(Wall B has a 3.31" tk space, 36.02" pards, and a 1.5" thick granite top - it correctly shows a 40.83" build height)

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 ,

I am trying to reproduce your issue without success. 

[2D Views - CTOP 1.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5752347/2D.Views.-.CTOP.1.pdf)

[2D Views - CTOP 2.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5752346/2D.Views.-.CTOP.2.pdf)

For me, they are correctly calculated, just as you said. 

I used 4.39" TK, 36.02" Pards, 0.75" for melamine, and 1.5" for HPL/Granite. 

For Granite and HPL it calculated 41.91" and melamine 41.16"

**Comment by nailsonlandim** [comment]
Hi @TedCC1209 

I've fixed it, Now if 2D views get cleaned and the countertops changed like melamine -> granite for instance, it changes the hashmark position and label properly.

I also have found a possible problem that @kategodfrey @sarahhightower and @JBTattersall will receive questions about it:

**Countertops on older designs**

If you change the countertop as mentioned on a new design, there is no problem, but in older projects the change wont be reflected. It's identified on 2D views as a countertop without a material (Mel, HPL, Gran.), like the image bellow.

![image](https://user-images.githubusercontent.com/70038700/103899719-8e43db80-50d5-11eb-9f0c-6a971fd44109.png)

The fix is pretty easy, just replace the countertop and it will behave as expected.

This is available at my master branch, which includes the hotfix and issue 261: https://github.com/nailsonlandim/SNaP-Dev/tree/master

If you find anything else unusual, just tell me.
