### ISSUE TITLE
"Classy-fy" SNaP Aesthetically

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#32]
I am hoping to "Classy-fy" SNaP to make SNaP more aesthetically pleasing to work with, especially as designers start using this in front of customers. Right now it looks kind of stuck in AutoCAD or back in the 80s or DOS. Essentially, creating a Classy "Theme" to Blender that would be the user default for SNaP. Some initial changes I would make are with the following:

- Putting our logo somewhere on the screen
- Color schemes that match Classy
- Change the fonts
- Anything else to make it prettier (think SketchUp)

I think collaborating with Katie Godfrey or Caitlin Denhalter on this would be beneficial. I think this might be something Teddy could do.

**Comment by TEDSTANDAGE** [comment]
We are looking for a white or light-colored background rather than black. Attached below are the colors we use here at Classy in our branding/media that we'd like utilized in the theme created:

[Media Kit_Brand Guidelines.pdf](https://github.com/CCDevNelson/Snap-Updates/files/4991300/Media.Kit_Brand.Guidelines.pdf)

**Comment by TylerStandage** [comment]
This is being handled in the new blender version, mostly by Josh.  We have a separate workstream on this.  I'll close this one.
