### ISSUE TITLE
Ability to have different melamine door/drawer face material compared to rest of closet

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#50]
I tried bringing this up before in Issue #4 , was told it was already in main Dev GitHub number 52 and therefore it was closed. However, number 52 in the Dev GitHub (which is currently closed) was about switching back to melamine doors/drawer faces after making them RP/wood so that was inapplicable (it being the same material as the rest of the closet). Dev GitHub Issue No. _47_ does ask for the ability to have 2 different materials selected in the same closet _generally_, but not specifically about just doors/drawer faces. That issue has sat there since January 2019... 

I want to start with just the doors/drawer faces and I think Teddy may be able to handle this one as we currently do have the ability to insert RP/wood doors & drawer faces that are different from the main material selection of the closet, so I think we could similarly have an option to insert Custom Color Melamine Doors/Drawer Faces and have another dropdown with the melamine colors for those custom doors/drawer faces. Teddy, let me know if you have any questions and if you think this is something you could attack. It is actually an important one if we want to start moving these into production.

**Comment by ClassyTeddy** [comment]
I believe I understand what you want to accomplish here, but at the moment I'm not even sure where to begin with how to attempt implementing it. I can look into it and come back to it, but I see this as something Ryan might know how to accomplish.

**Comment by TEDSTANDAGE** [comment]
We should probably pass this up to Ryan then

**Comment by TEDSTANDAGE** [comment]
I am able to now have a different melamine color for doors and drawer fronts in the drawing, but I am unsure the XML is reflecting it. Here is the drawing with a 24" wide section with doors and drawers, the closet being absolute acajou and the doors/drawer faces being Oxford White:

![image](https://user-images.githubusercontent.com/61025894/81319859-2b310f00-9045-11ea-89e9-fbae952a0078.png)

When I look at the XML, the doors, drawer faces, and the other materials of the closet have the same material IDM-0:

Here is cleat that should be absolute acajou saying it is IDM-0:

![image](https://user-images.githubusercontent.com/61025894/81320281-c924d980-9045-11ea-8873-fa8ece93273a.png)

The doors should be Oxford White but they also say IDM-0:

![image](https://user-images.githubusercontent.com/61025894/81320348-e6f23e80-9045-11ea-8d8b-6478faa0de47.png)

The drawer faces should also be Oxford White but they also say IDM-0:

![image](https://user-images.githubusercontent.com/61025894/81320416-fffaef80-9045-11ea-92db-b3f2f1a9c5e5.png)

IDM-0 is assigned as Absolute Acajou at the bottom of the XML file, and I do not see Oxford White anywhere:

![image](https://user-images.githubusercontent.com/61025894/81320521-2caf0700-9046-11ea-9eff-155aba3c01ee.png)

Perhaps I am doing something wrong, but that's what I am finding. Thanks, Ted

**Comment by RyanMDev** [comment]
Fix for this as well as correct edge banding skus for custom color doors/drawers is available with commit:  
CCDevNelson/SNaP-Dev@9a21a5da32fedcf6a41a7da3bff995bb50f84e22

**Comment by TEDSTANDAGE** [comment]
It looks to be exporting two separate colors now, thank you! I did basically the same job, with Oxford White doors/drawer faces with Absolute Acajou pards/cleats/shelves/etc:

![image](https://user-images.githubusercontent.com/61025894/81421159-dc977980-9105-11ea-966e-5d90d6e0cbe6.png)

I am wondering however why it now has IDM-0 (Absolute Acajou), IDM-1 (Oxford White), and IDM-2 (Absolute Acajou duplicate). IDM-0 and IDM-1 I understand, just not IDM-2 but maybe it is necessary?

![image](https://user-images.githubusercontent.com/61025894/81419385-01d6b880-9103-11ea-81ad-89196b0eedf9.png)


I looked for what was using the IDM-2 and it looks like melamine drawer box parts were exporting as that (sides, front, back material):

![image](https://user-images.githubusercontent.com/61025894/81419681-80335a80-9103-11ea-87d2-ce3baa1887d8.png)

Those melamine drawer box parts (sides, front, back) should be exporting as 1/2" Oxford White Paper G2 no matter the color of the closet (correct me if I am wrong Mark, but I believe the correct material is PM-000004).

Then, I looked and saw that the drawer box bottoms were exporting as IDM-0 (3/4 Absolute Acajou):

![image](https://user-images.githubusercontent.com/61025894/81420805-5713c980-9105-11ea-9300-fe605c2c957d.png)

Those (drawer box bottoms) should be exporting as 3/8" Oxford White Paper G1 for melamine drawer boxes (Again, correct me if I am wrong Mark, but I believe it is PM-000002). Maybe drawer box material isn't something we have addressed yet? 

NOTE: We should probably just create a new issue for exporting the correct drawer box materials.

**Comment by TEDSTANDAGE** [comment]
For discussion (no changes to be made on this yet)--Is it possible to have the melamine door/drawer face color just be a standard option chosen rather than making it something that is "custom" and having to replace each door/face after they are entered as if they were wood? Then when we put in doors/drawer faces they just default to the Door/Drawer face melamine color that is set. I'm just thinking that such since a majority of our jobs are Dura White closets with Panolam Oxford White doors/faces that it'd be easier. In COS currently we choose our door and drawer face color at the beginning in room settings.

**Comment by ClassyTeddy** [comment]
I definitely think that this is possible, but seeing how it currently has more customization with the ability to pick and choose which door and drawer faces are custom colored, this way might be the better option. Also, you can shift click on each door and replace them all with one click of the "Replace Selection" button.

**Comment by TEDSTANDAGE** [comment]
I think my preference would be to choose a door/face color as a setting rather than it be custom, and then integrate a "unique material" function for further customization of doors/faces like we do for 1/4" backs/cedar backs. 

I am also thinking in the case of a Dura White closet and Panolam Oxford White doors/faces, when a designer turns in a project for Sean/Jason/I to review before we send it out for production, how are we to know they replaced each and every door/face the "custom" way just by looking at the drawing? At least if the settings showed a Dura White closet with Panolam Oxford White door/faces we could see that.

**Comment by TEDSTANDAGE** [comment]
Further, the Melamine Glass Inset door is currently relating to the closet material:

![image](https://user-images.githubusercontent.com/61025894/81738450-95372300-944e-11ea-87b7-129397d40565.png)

If we end up making the doors/drawer face color a setting rather than a custom replacement, then is should relate to that color.  If we keep as-is as a custom replacement, then we need the option to relate to the "Custom Color Melamine Doors/Drawer Faces color".

This furthers me toward thinking the door/face material should be a standard setting rather than something custom.

**Comment by ClassyTeddy** [comment]
Making the doors and drawers just draw from a separate door color now seems more sensible to me. However, what do you mean when you say you want to add a unique material function? Like, unique material color, or actually unique materials, like using a specific wood?

**Comment by TEDSTANDAGE** [comment]
Teddy, check out the following for how the unique material feature works for cedar backs:

https://github.com/CCDevNelson/SNaP-Dev/issues/112

**Comment by TEDSTANDAGE** [comment]
The new changes look good to me with the exception of Hamper Faces. I didn't mention hamper faces in the OP so that's my bad, but those should be the same as the doors/drawer faces. The hamper faces seem to correctly relate to the door/drawer face material selection but the edges are matching the Edge Selection of the Closet rather than of the Doors/Drawer Faces:

![image](https://user-images.githubusercontent.com/61025894/82074868-3fea5400-9690-11ea-9d30-6b2bfe9cfb32.png)

Other than that I think it looks good. Also note that when this is merged with the Master, we then need to change some of the default settings--the new default closet material should be Dura White and the default door/drawer face material should be Oxford White, with all edges of the closet and doors/drawer faces defaulting to Oxford White.

**Comment by RyanMDev** [comment]
https://github.com/CCDevNelson/SNaP-Dev/issues/47#issuecomment-629390109

**Comment by TEDSTANDAGE** [comment]
SNaP now freezes/Does Not Respond when I try and add partitions with this branch (2-Different-Melamine-Materials-Assigned-#47). It happens when I try and just place them without setting up a room, as well as when I create a new project/room and try and enter them in there, etc. Confirming that I loaded SNaP defaults. Other branches still working fine so I'm not sure what broke.

![image](https://user-images.githubusercontent.com/61025894/82094694-6a4d0900-96b2-11ea-952c-4735ee54ec2f.png)

**Comment by RyanMDev** [comment]
This is a separate issue with the Dura White material.

For now, the following commit temporarily fixes the issue on this branch so testing of this issue can continue: 5f989cb774b6d7b534ae64a1a7873df1c0b197e6

**Comment by TEDSTANDAGE** [comment]
So the doors and drawer faces look good and look to be exporting the correct material. The Hamper faces ("Hamper Door") shows up the correct color material in the SNaP drawing but the XML export looks to be exporting it incorrectly as the closet material rather than the Door/Drawer Face material. Here is the closet with dura white closet materials and absolute acajou doors/drawer faces, with the hamper door appearing to be absolute acajou:

![image](https://user-images.githubusercontent.com/61025894/82221841-5cc39900-98d5-11ea-882b-d17e9fdde3d1.png)

However, the XML shows it as IDM-0 (dura white) rather than IDM-1 (absolute acajou):

![image](https://user-images.githubusercontent.com/61025894/82221959-841a6600-98d5-11ea-84f5-1c94a1df73f4.png)

Here is the door and the drawer faces correctly exporting as IDM-1:

![image](https://user-images.githubusercontent.com/61025894/82222184-c80d6b00-98d5-11ea-8d91-ecbe7dcf38b4.png)
