### ISSUE TITLE
Double Jewelry Drawer Box Option

### ISSUE THREAD

**Issue by TedClassy1209** [CCDevNelson/Snap-Updates#62]
Need to add a double jewelry drawer box option. In this scenario, there are two drawer boxes for one face--only the bottom box is secured to the drawer face and the other drawer box is set on a separate set of slides and does not have a drawer face. Whoever is assigned this issue please see me for sizing and application.

**Comment by ClassyTeddy** [comment]
Hey Ted, can I get some details on the sizing and placement on this?

**Comment by TEDSTANDAGE** [comment]
For 6H - 7H drawer face sizes only and for 16" and deeper sections, we should add the option for double jewelry boxes. In this scenario, there are two 4H drawer boxes (2" tall sides) for the one face with the bottom box being secured to the face (with the bottom of the bottom box being where a normal drawer box would be on a face) and the second top box not secured to the face but having its own drawer slides and above the other box (couldn't tell you the exact vertical location, just make sure it clears the bottom box).

Note that if there is a side lock in this scenario, the bottom box would have to be adjusted to a "True 4H" size with 2.68" tall sides, the top box would stay with the 2" tall sides.

**Comment by ClassyTeddy** [comment]
Kk

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Double-Jewelry-Drawer-Box` branch. The option is only available when the partition is 16" or deeper, and only for 6H and 7H drawers.

**Comment by SeanRadvan** [comment]
It looks like its working correctly, except the lock for "top" is placed
behind the drawer.

**Comment by TEDSTANDAGE** [comment]
Looking great, thank you Teddy. The vertical location of the "top" lock should be like a normal top lock for the drawer face size (it uses the KD above the drawer to lock so it will be placed near the top of the drawer face):

![image](https://user-images.githubusercontent.com/61025894/92141998-0cab0c80-edc8-11ea-954d-7e9b3753b8f1.png)

Also, let's fix the spelling of "Jewelry" in the drawer prompts. 

![image](https://user-images.githubusercontent.com/61025894/92140478-0320a500-edc6-11ea-9c7c-f39182327402.png)

Otherwise it looks good to me (the XML looks good from what I saw, etc.). 


Side note:
I will create a new issue for this, but when we show the drawers open on assemblies that have double jewelry, if possible, let's show the top drawer of the double jewelry option only coming out half as far as the rest of the drawers in the assembly:

![image](https://user-images.githubusercontent.com/61025894/92140742-5b57a700-edc6-11ea-8c87-8a68eab62a89.png)

**Comment by ClassyTeddy** [comment]
Ready for testing on the `Double-Jewelry-Drawer-Box` branch.

**Comment by TEDSTANDAGE** [comment]
Looks good to me, thank you Teddy
