### ISSUE TITLE
Force Double Door Option Enabled by default when door width is between 21" and 24"

### ISSUE THREAD

**Issue by ClassyTeddy** [CCDevNelson/Snap-Updates#66]
Want to add the feature where the "Force Double Door" prompt attached to doors is enabled by default when the door is placed into a partition between 21" and 24".

When the door's width is 24.01" or more, the door should be double doors no matter what.

When the door's width is 21" or less, the "Force Double Door" prompt should be disabled by default.

**Comment by meltnaz** [comment]
I think there is a check box in construction options tab in the tool shelf in the doors tab if you think this would be helpful.

![double door settings](https://user-images.githubusercontent.com/32275766/82592006-0a90ab00-9b55-11ea-9b75-8e16e81d0e96.png)

**Comment by riyajose96** [comment]
When the door's width is bewteen 21" and 24 , the "Force Double Door" prompt is enabled by default with a provision to turn it On and Off. 

Library item is on the branch -- riya-fixed.

**Comment by TEDSTANDAGE** [comment]
Let's have 21" exact come with the Force Double Door prompt enabled by default with the option to turn it off. Otherwise it looks good to me.

**Comment by riyajose96** [comment]
"Force Double Door" is enabled by default when the door is placed into a partition between 21" and 24". When the door's width is 24.1" or more, no matter what its made double doors.
Ready for testing.
Library item is on the branch -- riya-fixed.

**Comment by TEDSTANDAGE** [comment]
It is now forcing a double door for widths below 21". Here is is defaulting to a forced double door where the interior width is 19.01:

![image](https://user-images.githubusercontent.com/61025894/83042787-e6bae280-9ff6-11ea-9bff-9c2296c42f94.png)

Also it is not allowing a single door for an interior width of 24" anymore:

![image](https://user-images.githubusercontent.com/61025894/83042922-0baf5580-9ff7-11ea-999a-39003a4b9385.png)

Let me know if we need to discuss. This issue was almost perfect before, it just needed to include exactly 21" with the default forced double door enabled.

**Comment by riyajose96** [comment]
Issues are fixed. "Force Double Door" is enabled by default if the width is bewteen 21" and 24".
Library item is on the branch -- riya-fixed.

**Comment by TEDSTANDAGE** [comment]
Looks good to me

**Comment by ClassyTeddy** [comment]
It also looks good to me, I will go ahead and close it.
