### ISSUE TITLE
Rod Location showing Door/Drawer face dimensions

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#74]
I am wondering why our hanging prompts show the rod location dimensions as the door/drawer face size for that hole count rather than the partition size for that hole count (e.g. for 3H it says 3.62 instead of 4.53, for 4H it says 4.88 instead of 5.79, etc.). This is something that was probably set up a long while back, before even I was involved in this. I would think we would want the partition size displayed rather than the door/face dimensions, but perhaps there was a reason it was set up the way it is? If no one can think of a reason, I think we should change it to display the partition size for each hole count.

![image](https://user-images.githubusercontent.com/61025894/82564927-74e22500-9b2e-11ea-9b30-c6554ae71672.png)

**Comment by ClassyTeddy** [comment]
I believe the reason it is set up this way is because if the Rods used the panel heights, then the shelves would get misaligned easily. I quickly changed which list the Rods used, and the shelves clipped with the cleats as well as being oddly spaced apart. Also, while using a 37 Hole Partition, when I used a 37 Hole rod the rod would be one entire hole length below the bottom of the partition. It's better to keep the rods as they are now so that they align correctly in SNaP

**Comment by TEDSTANDAGE** [comment]
Can you have the dropdown display one thing but then have it calculate the location of the shelves/rod in the drawing on something else

**Comment by ClassyTeddy** [comment]
The rod location should now be showing panel heights but will use the door/drawer face heights. This is ready for testing on the "Branch_Short-Hang" branch.
