### ISSUE TITLE
Doors, drawer faces, hamper doors being sized incorrectly

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#81]
Doors, drawer faces, and hamper doors are being sized incorrectly. Here the left two sections have opening widths of 24" and the right section has an opening width of 18":

![image](https://user-images.githubusercontent.com/61025894/83559003-bc6e9680-a4c8-11ea-9f25-4e8e11195b50.png)

![image](https://user-images.githubusercontent.com/61025894/83559028-c395a480-a4c8-11ea-8151-50946bf6579a.png)

These are all half overlay doors/faces. For half overlay doors/faces, the width of single doors / drawer faces / hamper doors should be the section opening width plus 0.58". Double doors should be the opening width, divided by 2, plus 0.2". 

So, here, for the first section, the double doors should be 12.2" wide and the hamper face should be 24.58" wide; for the second section the single upper door should be 24.58" wide and the drawer faces should all be 24.58" wide; and for the third section the tall door should be 18.58" wide. 

However, the double doors are being exported at 12.25" wide instead of 12.2":

![image](https://user-images.githubusercontent.com/61025894/83559541-95649480-a4c9-11ea-94f1-8f2214075d4e.png)

The hamper face is being exported at 24.625" wide instead of 24.58":

![image](https://user-images.githubusercontent.com/61025894/83559618-b9c07100-a4c9-11ea-96e0-afbeca3b9b4b.png)

The single upper door is being exported at 24.625" wide instead of 24.58":

![image](https://user-images.githubusercontent.com/61025894/83559679-d361b880-a4c9-11ea-9343-80acce5a720d.png)

The drawer faces are being exported at 24.625" wide instead of 24.58":

![image](https://user-images.githubusercontent.com/61025894/83559716-e6748880-a4c9-11ea-8e90-83af286611e2.png)

And the tall door is being exported at 18.625" wide instead of 18.58":

![image](https://user-images.githubusercontent.com/61025894/83559763-f8eec200-a4c9-11ea-9108-af75dd9f7dcf.png)

The heights of the doors are also incorrect.

The double doors are being exported at 30.1112" tall even though I had them selected to be 24H, meaning they should be 30.08" tall:

![image](https://user-images.githubusercontent.com/61025894/83559906-32273200-a4ca-11ea-9e89-37e5b5c2c08a.png)

A 19H tall hamper face is being exported as 23.812" tall when is should be 23.78":

![image](https://user-images.githubusercontent.com/61025894/83560002-58e56880-a4ca-11ea-84ba-963cd2bb54bd.png)

The single upper door should be 26H when I said "Fill Opening" (62H pard minus 36H worth of drawers). A 26H door should be 32.60" tall, but it was exported as 33.3828":

![image](https://user-images.githubusercontent.com/61025894/83560162-a1048b00-a4ca-11ea-82f0-5624570f6ba5.png)

The 6H drawer faces are being exported nearly correctly at 7.3996" tall, though I don't know why they aren't just exported at the 7.40":

![image](https://user-images.githubusercontent.com/61025894/83560244-c5f8fe00-a4ca-11ea-9401-4b53dfe78b39.png)

Then the 62H tall single door should have been exported at 77.95" tall but was exported at 77.9833" tall:

![image](https://user-images.githubusercontent.com/61025894/83560345-ede86180-a4ca-11ea-9415-0aff3e19e308.png)

Here is the hole chart reference sheet for sizing the heights of doors/drawer faces:

![image](https://user-images.githubusercontent.com/61025894/83560606-5a636080-a4cb-11ea-9ba5-afa7a3ca0624.png)

Here are the full overlay width calculations: 

For Full overlay drawer faces and single doors, you take the exterior width (opening plus the two partitions) minus 0.25" for the width of those. For a pair of doors, you take the exterior width, minus 0.375", then divide by two for the width of each door.

Let me know if you have any questions. Teddy/Riya should be able to handle this one. Thanks

**Comment by ClassyTeddy** [comment]
This issue is fixed and ready for testing on the `Door/Drawer-Face-Overlay-Sizing-Fix` branch.

A quick list of what has changed and should be considered fixed once tested:

* Half overlay widths for single doors, drawer faces, and hamper door faces should now be calculating to `opening_width + 0.58"`

* Half overlay widths for double doors should now be calculating to `(opening_width/2) + 0.2"`

* Full overlay widths for single doors, drawer faces, and hamper door faces should now be calculating to `(opening_width + 1.5") - 0.25"`

* Full overlay widths for double doors should now be calculating to 
`((opening_width + 1.5")+0.375")/2)"`

*  Heights for single doors, double doors, drawer faces, and hamper door faces should now be calculating to to match the displayed height in the prompts menu.

* Heights for fill opening doors ***should*** now be calculating to to match the hole count of the opening. This one uses rounding, so it might be inaccurate on rare occasions, please let me know if it is.

* Updated doors to be a default 21H (This was done because the new height calculations were causing the door to be a far larger height with the previous default value. Side note, I can still change whatever the default for doors are, even back to what they were, I just had to change the value for the time being)

* Hampers now display hole count **and** inches, not just hole count.

* Hampers now retain their previous height selection when right clicked, not go back to the default 19H.

* Millimeter values for all `OPENING_HEIGHTS` and `FRONT_HEIGHTS` were changed slightly to more accurately reflect the Inch values (This shouldn't cause any problems with the drawing or anything, should just make some rounding added to the XML more accurate. Just writing it down in case it does cause issues.)

* The XML file now rounds inch values to the nearest hundredth, not ten thousandth.

-----------------------------------------------------------------------------------------
Some things that **weren't** fixed on this branch / need to watch out for:

* Opening above drawers being too large; This issue is fixed and is ready for testing on the `Teddy-Door-KD-Fixes branch`.

* The fill opening option above drawers might not size the door face properly, but I can't really take a look at it until both this branch and the above mentioned branch get merged.

* Going to reiterate this, but the fill opening option for doors forces them to be rounded to the nearest hundredth of an inch, and it may not round properly on one or two of the possible hole sizes. Please keep this in mind when testing. 

-----------------------------------------------------------------------------------------

Please let me know if any of the above made changes should be adjusted. Thanks

**Comment by TEDSTANDAGE** [comment]
Will have multiple comments on this as I go through testing it. 

You wrote this in your comment above:

Full overlay widths for double doors should now be calculating to
((opening_width + 1.5")+0.375")/2)"

I think you actually wrote it correctly in the code where it is MINUS 0.375" instead of adding it. It looks to be correct in my initial testing at least.

**Comment by TEDSTANDAGE** [comment]
The widths are looking great from what I can see, as are the heights of drawer faces and hampers. A few issues I'm finding with door heights, however. 

In the following example, I chose base doors to be 31H tall (38.90" tall). However, it looks to be entering 32H doors (40.16" tall):

![image](https://user-images.githubusercontent.com/61025894/83900028-43f91700-a70e-11ea-8bb4-4c9530f06ad1.png)

For the following upper doors I chose them to be 29H tall (36.38" tall). However, it looks to be entering 30H doors (37.64" tall):

![image](https://user-images.githubusercontent.com/61025894/83900133-6db23e00-a70e-11ea-86f1-ad3370e02f2e.png)

This tall door using fill opening looks to be correctly entering a 62H door (77.95") for the 62H partition: 

![image](https://user-images.githubusercontent.com/61025894/83900295-a18d6380-a70e-11ea-9810-8deee506b666.png)

And this upper door is correctly putting in the selected 28H door (35.12" tall):

![image](https://user-images.githubusercontent.com/61025894/83901128-182a6100-a70f-11ea-903d-a1b80c267037.png)

I can't figure out why/when it happens exactly...

**Comment by TEDSTANDAGE** [comment]
So actually the issue might be with the prompt reloading incorrectly when I go back into it. Here, I chose the base doors to be 32H (40.16") and it correctly made the doors 40.16":

![image](https://user-images.githubusercontent.com/61025894/83901737-13b27800-a710-11ea-96e0-4f169436eea1.png)

When I click out of the door prompt menu and get back into it, however, it says 31H doors (38.90") in the prompt but the door stays 32H (40.16") like I had previously selected:

![image](https://user-images.githubusercontent.com/61025894/83901866-49576100-a710-11ea-97e4-d19ce86df9d3.png)

So, this looks to actually be an issue with the prompt menu display when getting back into it and not with the doors being placed in as the wrong height.

**Comment by ClassyTeddy** [comment]
A fix door prompts displaying the wrong height is available on the `Door/Drawer-Face-Overlay-Sizing-Fix` branch and is ready for testing.

**Comment by TEDSTANDAGE** [comment]
Looks good to me.

**Comment by ClassyTeddy** [comment]
I could take a look at it now, but the `Teddy-Door-KD-Fixes` branch doesn't have the changes I already made to fill opening on the `Door/Drawer-Face-Overlay-Sizing-Fix` branch. So I think we should look at that specific scenario again when the branches get merged into the master to see how they interact.
